#!/usr/bin/env bash

# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset

COMPILE_DB=$(dirname $(realpath $0))

function runTidyWithinDocker() {
    /usr/bin/clang-tidy "$@" -p "${COMPILE_DB}" --config="$(cat /workspaces/dcgm/.clang-tidy)" --extra-arg="-Wno-unknown-warning-option" --extra-arg="-isystem/opt/cross/x86_64-linux-gnu/include"
}

function runTidyUsingDocker() {
    ./intodocker.sh ./clang-tidy "$@"
}

if [[ ${DCGM_BUILD_INSIDE_DOCKER:-} -eq 1 ]]; then
    runTidyWithinDocker "$@"
else
    runTidyUsingDocker "$@"
fi
