#!/usr/bin/env bash

# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$DCGM_BUILD_INSIDE_DOCKER" = 1 ]; then
    for file in $(find . "(" -not -ipath "./_out/*" -a -not -ipath "./sdk/*" -a -not -ipath "./PerfWorks/*" ")" \
                  -a "(" -iname "*.h" -o -iname "*.hpp" -o -iname "*.c" -o -iname "*.cpp" ")"); do

        pushd $(dirname $(realpath $file)) >/dev/null
        clang-format -i --style=file $(basename $file) &
        popd >/dev/null

    done

    wait
else
    ./intodocker.sh -- bash -c "$0 $@"
fi
