#!/usr/bin/env bash

# Copyright (c) 2023-2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

TOP_LEVEL_DIR=$(pwd)

if [ "$DCGM_BUILD_INSIDE_DOCKER" != 1 ]; then
    ./intodocker.sh -- bash "$0" "$@"
    exit $?
fi

function format_cxx() {
    find "${TOP_LEVEL_DIR}" -type f \
        "(" -name "*.[ch]" -o -name "*.[ch]pp" ")" \
        -print0 \
        | xargs -0 -n 1 -P 0 clang-format -i
}
 
function format_python() {
    if ! command -v autopep8 &> /dev/null; then
        echo "WARNING: autopep8 not found. Python files will NOT be formatted." >&2
        return
    fi

    autopep8 --in-place --recursive --jobs 0 "${TOP_LEVEL_DIR}"
}

format_cxx
format_python
