# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---

services:
  dcgm-common-host-software:
    build:
      context: .
      dockerfile: dockerfiles/common-host-software.Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE:-ubuntu:24.04}
      tags:
        - ${REGISTRY:-dcgm}/common-host-software:${TAG:-latest}
  dcgm-toolchain-x86_64:
    depends_on:
      - dcgm-common-host-software
    build:
      context: .
      dockerfile: dockerfiles/target-toolchain.Dockerfile
      args:
        - ARCHITECTURE=x86_64
        - CROSSTOOL_BASE_IMAGE=${BASE_IMAGE:-ubuntu:24.04}
        - CROSSTOOL_SHA512SUM=${CROSSTOOL_SHA512SUM:-5297954cfdf7e59493e91060c996b8fe7843d155378066faa1d26a23a417b17cc4d008ed93d6408db89cf1b8c336729e22b5a104d6ccec096bdc2b958977ec41}
        - CROSSTOOL_URL=${CROSSTOOL_URL:-https://github.com/crosstool-ng/crosstool-ng/archive/c5a17024a9af713a218d533fe78b7cf9a02ec67e.tar.gz}
        - TOOLCHAIN_BASE_IMAGE=${REGISTRY:-dcgm}/common-host-software:${TAG:-latest}
      tags:
        - ${REGISTRY:-dcgm}/toolchain-x86_64:${TAG:-latest}
  dcgmbuild-x86_64:
    depends_on:
      - dcgm-toolchain-x86_64
    build:
      context: .
      dockerfile: dockerfiles/dcgmbuild.Dockerfile
      args:
        - BASE_IMAGE=${REGISTRY:-dcgm}/toolchain-x86_64:${TAG:-latest}
      tags:
        - ${REGISTRY:-dcgm}/dcgmbuild:${TAG:-latest}-x86_64
        - dcgmbuild-x86_64
  dcgm-toolchain-aarch64:
    depends_on:
      - dcgm-common-host-software
    build:
      context: .
      dockerfile: dockerfiles/target-toolchain.Dockerfile
      args:
        - ARCHITECTURE=aarch64
        - CROSSTOOL_BASE_IMAGE=${BASE_IMAGE:-ubuntu:24.04}
        - CROSSTOOL_SHA512SUM=${CROSSTOOL_SHA512SUM:-5297954cfdf7e59493e91060c996b8fe7843d155378066faa1d26a23a417b17cc4d008ed93d6408db89cf1b8c336729e22b5a104d6ccec096bdc2b958977ec41}
        - CROSSTOOL_URL=${CROSSTOOL_URL:-https://github.com/crosstool-ng/crosstool-ng/archive/c5a17024a9af713a218d533fe78b7cf9a02ec67e.tar.gz}
        - TOOLCHAIN_BASE_IMAGE=${REGISTRY:-dcgm}/common-host-software:${TAG:-latest}
      tags:
        - ${REGISTRY:-dcgm}/toolchain-aarch64:${TAG:-latest}
  dcgmbuild-aarch64:
    depends_on:
      - dcgm-toolchain-aarch64
    build:
      context: .
      dockerfile: dockerfiles/dcgmbuild.Dockerfile
      args:
        - BASE_IMAGE=${REGISTRY:-dcgm}/toolchain-aarch64:${TAG:-latest}
      tags:
        - ${REGISTRY:-dcgm}/dcgmbuild:${TAG:-latest}-aarch64
        - dcgmbuild-aarch64
