/*
 * Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: This code is auto-generated by generate_nvml_stubs.py
 * DO NOT EDIT MANUALLY
 */


// clang-format off
#pragma once

#include <nvml.h>
// The following snippet is generated from write_injection_structs_header
typedef union
{
    char *Str;
    char Char;
    double *DoublePtr;
    double Double;
    int *IntPtr;
    int Int;
    long *LongPtr;
    long Long;
    long long *LongLongPtr;
    long long LongLong;
    nvmlAccountingStats_t *AccountingStatsPtr;
    nvmlAccountingStats_t AccountingStats;
    nvmlAffinityScope_t *AffinityScopePtr;
    nvmlAffinityScope_t AffinityScope;
    nvmlBAR1Memory_t *BAR1MemoryPtr;
    nvmlBAR1Memory_t BAR1Memory;
    nvmlBrandType_t *BrandTypePtr;
    nvmlBrandType_t BrandType;
    nvmlBridgeChipHierarchy_t *BridgeChipHierarchyPtr;
    nvmlBridgeChipHierarchy_t BridgeChipHierarchy;
    nvmlBridgeChipInfo_t *BridgeChipInfoPtr;
    nvmlBridgeChipInfo_t BridgeChipInfo;
    nvmlBridgeChipType_t *BridgeChipTypePtr;
    nvmlBridgeChipType_t BridgeChipType;
    nvmlBusType_t *BusTypePtr;
    nvmlBusType_t BusType;
    nvmlC2cModeInfo_v1_t *C2cModeInfo_v1Ptr;
    nvmlC2cModeInfo_v1_t C2cModeInfo_v1;
    nvmlClkMonFaultInfo_t *ClkMonFaultInfoPtr;
    nvmlClkMonFaultInfo_t ClkMonFaultInfo;
    nvmlClkMonStatus_t *ClkMonStatusPtr;
    nvmlClkMonStatus_t ClkMonStatus;
    nvmlClockId_t *ClockIdPtr;
    nvmlClockId_t ClockId;
    nvmlClockLimitId_t *ClockLimitIdPtr;
    nvmlClockLimitId_t ClockLimitId;
    nvmlClockOffset_t *ClockOffsetPtr;
    nvmlClockOffset_t ClockOffset;
    nvmlClockType_t *ClockTypePtr;
    nvmlClockType_t ClockType;
    nvmlComputeInstanceInfo_t *ComputeInstanceInfoPtr;
    nvmlComputeInstanceInfo_t ComputeInstanceInfo;
    nvmlComputeInstancePlacement_t *ComputeInstancePlacementPtr;
    nvmlComputeInstancePlacement_t ComputeInstancePlacement;
    nvmlComputeInstanceProfileInfo_t *ComputeInstanceProfileInfoPtr;
    nvmlComputeInstanceProfileInfo_t ComputeInstanceProfileInfo;
    nvmlComputeInstanceProfileInfo_v2_t *ComputeInstanceProfileInfo_v2Ptr;
    nvmlComputeInstanceProfileInfo_v2_t ComputeInstanceProfileInfo_v2;
    nvmlComputeInstanceProfileInfo_v3_t *ComputeInstanceProfileInfo_v3Ptr;
    nvmlComputeInstanceProfileInfo_v3_t ComputeInstanceProfileInfo_v3;
    nvmlComputeInstance_t *ComputeInstancePtr;
    nvmlComputeInstance_t ComputeInstance;
    nvmlComputeMode_t *ComputeModePtr;
    nvmlComputeMode_t ComputeMode;
    nvmlConfComputeGetKeyRotationThresholdInfo_v1_t *ConfComputeGetKeyRotationThresholdInfo_v1Ptr;
    nvmlConfComputeGetKeyRotationThresholdInfo_v1_t ConfComputeGetKeyRotationThresholdInfo_v1;
    nvmlConfComputeGpuAttestationReport_t *ConfComputeGpuAttestationReportPtr;
    nvmlConfComputeGpuAttestationReport_t ConfComputeGpuAttestationReport;
    nvmlConfComputeGpuCertificate_t *ConfComputeGpuCertificatePtr;
    nvmlConfComputeGpuCertificate_t ConfComputeGpuCertificate;
    nvmlConfComputeMemSizeInfo_t *ConfComputeMemSizeInfoPtr;
    nvmlConfComputeMemSizeInfo_t ConfComputeMemSizeInfo;
    nvmlConfComputeSetKeyRotationThresholdInfo_v1_t *ConfComputeSetKeyRotationThresholdInfo_v1Ptr;
    nvmlConfComputeSetKeyRotationThresholdInfo_v1_t ConfComputeSetKeyRotationThresholdInfo_v1;
    nvmlConfComputeSystemCaps_t *ConfComputeSystemCapsPtr;
    nvmlConfComputeSystemCaps_t ConfComputeSystemCaps;
    nvmlConfComputeSystemState_t *ConfComputeSystemStatePtr;
    nvmlConfComputeSystemState_t ConfComputeSystemState;
    nvmlCoolerControl_t *CoolerControlPtr;
    nvmlCoolerControl_t CoolerControl;
    nvmlCoolerInfo_t *CoolerInfoPtr;
    nvmlCoolerInfo_t CoolerInfo;
    nvmlCoolerTarget_t *CoolerTargetPtr;
    nvmlCoolerTarget_t CoolerTarget;
    nvmlDetachGpuState_t *DetachGpuStatePtr;
    nvmlDetachGpuState_t DetachGpuState;
    nvmlDeviceArchitecture_t *DeviceArchitecturePtr;
    nvmlDeviceArchitecture_t DeviceArchitecture;
    nvmlDeviceAttributes_t *DeviceAttributesPtr;
    nvmlDeviceAttributes_t DeviceAttributes;
    nvmlDeviceCapabilities_t *DeviceCapabilitiesPtr;
    nvmlDeviceCapabilities_t DeviceCapabilities;
    nvmlDeviceCurrentClockFreqs_t *DeviceCurrentClockFreqsPtr;
    nvmlDeviceCurrentClockFreqs_t DeviceCurrentClockFreqs;
    nvmlDeviceGpuRecoveryAction_t *DeviceGpuRecoveryActionPtr;
    nvmlDeviceGpuRecoveryAction_t DeviceGpuRecoveryAction;
    nvmlDevicePerfModes_t *DevicePerfModesPtr;
    nvmlDevicePerfModes_t DevicePerfModes;
    nvmlDeviceVgpuCapability_t *DeviceVgpuCapabilityPtr;
    nvmlDeviceVgpuCapability_t DeviceVgpuCapability;
    nvmlDevice_t *DevicePtr;
    nvmlDevice_t Device;
    nvmlDriverModel_t *DriverModelPtr;
    nvmlDriverModel_t DriverModel;
    nvmlEccCounterType_t *EccCounterTypePtr;
    nvmlEccCounterType_t EccCounterType;
    nvmlEccErrorCounts_t *EccErrorCountsPtr;
    nvmlEccErrorCounts_t EccErrorCounts;
    nvmlEccSramErrorStatus_t *EccSramErrorStatusPtr;
    nvmlEccSramErrorStatus_t EccSramErrorStatus;
    nvmlEnableState_t *EnableStatePtr;
    nvmlEnableState_t EnableState;
    nvmlEncoderSessionInfo_t *EncoderSessionInfoPtr;
    nvmlEncoderSessionInfo_t EncoderSessionInfo;
    nvmlEncoderType_t *EncoderTypePtr;
    nvmlEncoderType_t EncoderType;
    nvmlEventData_t *EventDataPtr;
    nvmlEventData_t EventData;
    nvmlEventSet_t *EventSetPtr;
    nvmlEventSet_t EventSet;
    nvmlExcludedDeviceInfo_t *ExcludedDeviceInfoPtr;
    nvmlExcludedDeviceInfo_t ExcludedDeviceInfo;
    nvmlFBCSessionInfo_t *FBCSessionInfoPtr;
    nvmlFBCSessionInfo_t FBCSessionInfo;
    nvmlFBCSessionType_t *FBCSessionTypePtr;
    nvmlFBCSessionType_t FBCSessionType;
    nvmlFBCStats_t *FBCStatsPtr;
    nvmlFBCStats_t FBCStats;
    nvmlFanControlPolicy_t *FanControlPolicyPtr;
    nvmlFanControlPolicy_t FanControlPolicy;
    nvmlFanSpeedInfo_t *FanSpeedInfoPtr;
    nvmlFanSpeedInfo_t FanSpeedInfo;
    nvmlFanState_t *FanStatePtr;
    nvmlFanState_t FanState;
    nvmlFieldValue_t *FieldValuePtr;
    nvmlFieldValue_t FieldValue;
    nvmlGpmMetricId_t *GpmMetricIdPtr;
    nvmlGpmMetricId_t GpmMetricId;
    nvmlGpmMetric_t *GpmMetricPtr;
    nvmlGpmMetric_t GpmMetric;
    nvmlGpmMetricsGet_t *GpmMetricsGetPtr;
    nvmlGpmMetricsGet_t GpmMetricsGet;
    nvmlGpmSample_t *GpmSamplePtr;
    nvmlGpmSample_t GpmSample;
    nvmlGpmSupport_t *GpmSupportPtr;
    nvmlGpmSupport_t GpmSupport;
    nvmlGpuDynamicPstatesInfo_t *GpuDynamicPstatesInfoPtr;
    nvmlGpuDynamicPstatesInfo_t GpuDynamicPstatesInfo;
    nvmlGpuFabricInfoV_t *GpuFabricInfoVPtr;
    nvmlGpuFabricInfoV_t GpuFabricInfoV;
    nvmlGpuFabricInfo_t *GpuFabricInfoPtr;
    nvmlGpuFabricInfo_t GpuFabricInfo;
    nvmlGpuFabricState_t *GpuFabricStatePtr;
    nvmlGpuFabricState_t GpuFabricState;
    nvmlGpuInstanceInfo_t *GpuInstanceInfoPtr;
    nvmlGpuInstanceInfo_t GpuInstanceInfo;
    nvmlGpuInstancePlacement_t *GpuInstancePlacementPtr;
    nvmlGpuInstancePlacement_t GpuInstancePlacement;
    nvmlGpuInstanceProfileInfo_t *GpuInstanceProfileInfoPtr;
    nvmlGpuInstanceProfileInfo_t GpuInstanceProfileInfo;
    nvmlGpuInstanceProfileInfo_v2_t *GpuInstanceProfileInfo_v2Ptr;
    nvmlGpuInstanceProfileInfo_v2_t GpuInstanceProfileInfo_v2;
    nvmlGpuInstanceProfileInfo_v3_t *GpuInstanceProfileInfo_v3Ptr;
    nvmlGpuInstanceProfileInfo_v3_t GpuInstanceProfileInfo_v3;
    nvmlGpuInstance_t *GpuInstancePtr;
    nvmlGpuInstance_t GpuInstance;
    nvmlGpuOperationMode_t *GpuOperationModePtr;
    nvmlGpuOperationMode_t GpuOperationMode;
    nvmlGpuP2PCapsIndex_t *GpuP2PCapsIndexPtr;
    nvmlGpuP2PCapsIndex_t GpuP2PCapsIndex;
    nvmlGpuP2PStatus_t *GpuP2PStatusPtr;
    nvmlGpuP2PStatus_t GpuP2PStatus;
    nvmlGpuThermalSettings_t *GpuThermalSettingsPtr;
    nvmlGpuThermalSettings_t GpuThermalSettings;
    nvmlGpuTopologyLevel_t *GpuTopologyLevelPtr;
    nvmlGpuTopologyLevel_t GpuTopologyLevel;
    nvmlGpuUtilizationDomainId_t *GpuUtilizationDomainIdPtr;
    nvmlGpuUtilizationDomainId_t GpuUtilizationDomainId;
    nvmlGpuVirtualizationMode_t *GpuVirtualizationModePtr;
    nvmlGpuVirtualizationMode_t GpuVirtualizationMode;
    nvmlGridLicensableFeature_t *GridLicensableFeaturePtr;
    nvmlGridLicensableFeature_t GridLicensableFeature;
    nvmlGridLicensableFeatures_t *GridLicensableFeaturesPtr;
    nvmlGridLicensableFeatures_t GridLicensableFeatures;
    nvmlGridLicenseExpiry_t *GridLicenseExpiryPtr;
    nvmlGridLicenseExpiry_t GridLicenseExpiry;
    nvmlGridLicenseFeatureCode_t *GridLicenseFeatureCodePtr;
    nvmlGridLicenseFeatureCode_t GridLicenseFeatureCode;
    nvmlHostVgpuMode_t *HostVgpuModePtr;
    nvmlHostVgpuMode_t HostVgpuMode;
    nvmlHwbcEntry_t *HwbcEntryPtr;
    nvmlHwbcEntry_t HwbcEntry;
    nvmlInforomObject_t *InforomObjectPtr;
    nvmlInforomObject_t InforomObject;
    nvmlIntNvLinkDeviceType_t *IntNvLinkDeviceTypePtr;
    nvmlIntNvLinkDeviceType_t IntNvLinkDeviceType;
    nvmlLedColor_t *LedColorPtr;
    nvmlLedColor_t LedColor;
    nvmlLedState_t *LedStatePtr;
    nvmlLedState_t LedState;
    nvmlMarginTemperature_t *MarginTemperaturePtr;
    nvmlMarginTemperature_t MarginTemperature;
    nvmlMask255_t *Mask255Ptr;
    nvmlMask255_t Mask255;
    nvmlMemoryErrorType_t *MemoryErrorTypePtr;
    nvmlMemoryErrorType_t MemoryErrorType;
    nvmlMemoryLocation_t *MemoryLocationPtr;
    nvmlMemoryLocation_t MemoryLocation;
    nvmlMemory_t *MemoryPtr;
    nvmlMemory_t Memory;
    nvmlMemory_v2_t *Memory_v2Ptr;
    nvmlMemory_v2_t Memory_v2;
    nvmlNvLinkCapability_t *NvLinkCapabilityPtr;
    nvmlNvLinkCapability_t NvLinkCapability;
    nvmlNvLinkErrorCounter_t *NvLinkErrorCounterPtr;
    nvmlNvLinkErrorCounter_t NvLinkErrorCounter;
    nvmlNvLinkPowerThres_t *NvLinkPowerThresPtr;
    nvmlNvLinkPowerThres_t NvLinkPowerThres;
    nvmlNvLinkUtilizationControl_t *NvLinkUtilizationControlPtr;
    nvmlNvLinkUtilizationControl_t NvLinkUtilizationControl;
    nvmlNvLinkUtilizationCountPktTypes_t *NvLinkUtilizationCountPktTypesPtr;
    nvmlNvLinkUtilizationCountPktTypes_t NvLinkUtilizationCountPktTypes;
    nvmlNvLinkUtilizationCountUnits_t *NvLinkUtilizationCountUnitsPtr;
    nvmlNvLinkUtilizationCountUnits_t NvLinkUtilizationCountUnits;
    nvmlNvlinkVersion_t *NvlinkVersionPtr;
    nvmlNvlinkVersion_t NvlinkVersion;
    nvmlPSUInfo_t *PSUInfoPtr;
    nvmlPSUInfo_t PSUInfo;
    nvmlPageRetirementCause_t *PageRetirementCausePtr;
    nvmlPageRetirementCause_t PageRetirementCause;
    nvmlPciInfoExt_t *PciInfoExtPtr;
    nvmlPciInfoExt_t PciInfoExt;
    nvmlPciInfo_t *PciInfoPtr;
    nvmlPciInfo_t PciInfo;
    nvmlPcieLinkState_t *PcieLinkStatePtr;
    nvmlPcieLinkState_t PcieLinkState;
    nvmlPcieUtilCounter_t *PcieUtilCounterPtr;
    nvmlPcieUtilCounter_t PcieUtilCounter;
    nvmlPerfPolicyType_t *PerfPolicyTypePtr;
    nvmlPerfPolicyType_t PerfPolicyType;
    nvmlPlatformInfo_t *PlatformInfoPtr;
    nvmlPlatformInfo_t PlatformInfo;
    nvmlPlatformInfo_v1_t *PlatformInfo_v1Ptr;
    nvmlPlatformInfo_v1_t PlatformInfo_v1;
    nvmlPowerProfileOperation_t *PowerProfileOperationPtr;
    nvmlPowerProfileOperation_t PowerProfileOperation;
    nvmlPowerProfileType_t *PowerProfileTypePtr;
    nvmlPowerProfileType_t PowerProfileType;
    nvmlPowerScopeType_t *PowerScopeTypePtr;
    nvmlPowerScopeType_t PowerScopeType;
    nvmlPowerSource_t *PowerSourcePtr;
    nvmlPowerSource_t PowerSource;
    nvmlPowerValue_v2_t *PowerValue_v2Ptr;
    nvmlPowerValue_v2_t PowerValue_v2;
    nvmlProcessDetailList_t *ProcessDetailListPtr;
    nvmlProcessDetailList_t ProcessDetailList;
    nvmlProcessDetail_v1_t *ProcessDetail_v1Ptr;
    nvmlProcessDetail_v1_t ProcessDetail_v1;
    nvmlProcessInfo_t *ProcessInfoPtr;
    nvmlProcessInfo_t ProcessInfo;
    nvmlProcessInfo_v1_t *ProcessInfo_v1Ptr;
    nvmlProcessInfo_v1_t ProcessInfo_v1;
    nvmlProcessUtilizationInfo_v1_t *ProcessUtilizationInfo_v1Ptr;
    nvmlProcessUtilizationInfo_v1_t ProcessUtilizationInfo_v1;
    nvmlProcessUtilizationSample_t *ProcessUtilizationSamplePtr;
    nvmlProcessUtilizationSample_t ProcessUtilizationSample;
    nvmlProcessesUtilizationInfo_t *ProcessesUtilizationInfoPtr;
    nvmlProcessesUtilizationInfo_t ProcessesUtilizationInfo;
    nvmlPstates_t *PstatesPtr;
    nvmlPstates_t Pstates;
    nvmlRestrictedAPI_t *RestrictedAPIPtr;
    nvmlRestrictedAPI_t RestrictedAPI;
    nvmlReturn_t *ReturnPtr;
    nvmlReturn_t Return;
    nvmlRowRemapperHistogramValues_t *RowRemapperHistogramValuesPtr;
    nvmlRowRemapperHistogramValues_t RowRemapperHistogramValues;
    nvmlSample_t *SamplePtr;
    nvmlSample_t Sample;
    nvmlSamplingType_t *SamplingTypePtr;
    nvmlSamplingType_t SamplingType;
    nvmlSystemConfComputeSettings_t *SystemConfComputeSettingsPtr;
    nvmlSystemConfComputeSettings_t SystemConfComputeSettings;
    nvmlSystemDriverBranchInfo_t *SystemDriverBranchInfoPtr;
    nvmlSystemDriverBranchInfo_t SystemDriverBranchInfo;
    nvmlSystemEventData_v1_t *SystemEventData_v1Ptr;
    nvmlSystemEventData_v1_t SystemEventData_v1;
    nvmlSystemEventSetCreateRequest_t *SystemEventSetCreateRequestPtr;
    nvmlSystemEventSetCreateRequest_t SystemEventSetCreateRequest;
    nvmlSystemEventSetFreeRequest_t *SystemEventSetFreeRequestPtr;
    nvmlSystemEventSetFreeRequest_t SystemEventSetFreeRequest;
    nvmlSystemEventSetWaitRequest_t *SystemEventSetWaitRequestPtr;
    nvmlSystemEventSetWaitRequest_t SystemEventSetWaitRequest;
    nvmlSystemRegisterEventRequest_t *SystemRegisterEventRequestPtr;
    nvmlSystemRegisterEventRequest_t SystemRegisterEventRequest;
    nvmlTemperatureSensors_t *TemperatureSensorsPtr;
    nvmlTemperatureSensors_t TemperatureSensors;
    nvmlTemperatureThresholds_t *TemperatureThresholdsPtr;
    nvmlTemperatureThresholds_t TemperatureThresholds;
    nvmlTemperature_t *TemperaturePtr;
    nvmlTemperature_t Temperature;
    nvmlThermalController_t *ThermalControllerPtr;
    nvmlThermalController_t ThermalController;
    nvmlThermalTarget_t *ThermalTargetPtr;
    nvmlThermalTarget_t ThermalTarget;
    nvmlUnitFanInfo_t *UnitFanInfoPtr;
    nvmlUnitFanInfo_t UnitFanInfo;
    nvmlUnitFanSpeeds_t *UnitFanSpeedsPtr;
    nvmlUnitFanSpeeds_t UnitFanSpeeds;
    nvmlUnitInfo_t *UnitInfoPtr;
    nvmlUnitInfo_t UnitInfo;
    nvmlUnit_t *UnitPtr;
    nvmlUnit_t Unit;
    nvmlUtilization_t *UtilizationPtr;
    nvmlUtilization_t Utilization;
    nvmlValueType_t *ValueTypePtr;
    nvmlValueType_t ValueType;
    nvmlVgpuCapability_t *VgpuCapabilityPtr;
    nvmlVgpuCapability_t VgpuCapability;
    nvmlVgpuDriverCapability_t *VgpuDriverCapabilityPtr;
    nvmlVgpuDriverCapability_t VgpuDriverCapability;
    nvmlVgpuGuestInfoState_t *VgpuGuestInfoStatePtr;
    nvmlVgpuGuestInfoState_t VgpuGuestInfoState;
    nvmlVgpuHeterogeneousMode_t *VgpuHeterogeneousModePtr;
    nvmlVgpuHeterogeneousMode_t VgpuHeterogeneousMode;
    nvmlVgpuInstanceUtilizationInfo_v1_t *VgpuInstanceUtilizationInfo_v1Ptr;
    nvmlVgpuInstanceUtilizationInfo_v1_t VgpuInstanceUtilizationInfo_v1;
    nvmlVgpuInstanceUtilizationSample_t *VgpuInstanceUtilizationSamplePtr;
    nvmlVgpuInstanceUtilizationSample_t VgpuInstanceUtilizationSample;
    nvmlVgpuInstance_t *VgpuInstancePtr;
    nvmlVgpuInstance_t VgpuInstance;
    nvmlVgpuInstancesUtilizationInfo_t *VgpuInstancesUtilizationInfoPtr;
    nvmlVgpuInstancesUtilizationInfo_t VgpuInstancesUtilizationInfo;
    nvmlVgpuLicenseExpiry_t *VgpuLicenseExpiryPtr;
    nvmlVgpuLicenseExpiry_t VgpuLicenseExpiry;
    nvmlVgpuLicenseInfo_t *VgpuLicenseInfoPtr;
    nvmlVgpuLicenseInfo_t VgpuLicenseInfo;
    nvmlVgpuMetadata_t *VgpuMetadataPtr;
    nvmlVgpuMetadata_t VgpuMetadata;
    nvmlVgpuPgpuCompatibilityLimitCode_t *VgpuPgpuCompatibilityLimitCodePtr;
    nvmlVgpuPgpuCompatibilityLimitCode_t VgpuPgpuCompatibilityLimitCode;
    nvmlVgpuPgpuCompatibility_t *VgpuPgpuCompatibilityPtr;
    nvmlVgpuPgpuCompatibility_t VgpuPgpuCompatibility;
    nvmlVgpuPgpuMetadata_t *VgpuPgpuMetadataPtr;
    nvmlVgpuPgpuMetadata_t VgpuPgpuMetadata;
    nvmlVgpuPlacementId_t *VgpuPlacementIdPtr;
    nvmlVgpuPlacementId_t VgpuPlacementId;
    nvmlVgpuPlacementList_t *VgpuPlacementListPtr;
    nvmlVgpuPlacementList_t VgpuPlacementList;
    nvmlVgpuPlacementList_v1_t *VgpuPlacementList_v1Ptr;
    nvmlVgpuPlacementList_v1_t VgpuPlacementList_v1;
    nvmlVgpuProcessUtilizationInfo_v1_t *VgpuProcessUtilizationInfo_v1Ptr;
    nvmlVgpuProcessUtilizationInfo_v1_t VgpuProcessUtilizationInfo_v1;
    nvmlVgpuProcessUtilizationSample_t *VgpuProcessUtilizationSamplePtr;
    nvmlVgpuProcessUtilizationSample_t VgpuProcessUtilizationSample;
    nvmlVgpuProcessesUtilizationInfo_t *VgpuProcessesUtilizationInfoPtr;
    nvmlVgpuProcessesUtilizationInfo_t VgpuProcessesUtilizationInfo;
    nvmlVgpuRuntimeState_t *VgpuRuntimeStatePtr;
    nvmlVgpuRuntimeState_t VgpuRuntimeState;
    nvmlVgpuSchedulerCapabilities_t *VgpuSchedulerCapabilitiesPtr;
    nvmlVgpuSchedulerCapabilities_t VgpuSchedulerCapabilities;
    nvmlVgpuSchedulerGetState_t *VgpuSchedulerGetStatePtr;
    nvmlVgpuSchedulerGetState_t VgpuSchedulerGetState;
    nvmlVgpuSchedulerLogEntry_t *VgpuSchedulerLogEntryPtr;
    nvmlVgpuSchedulerLogEntry_t VgpuSchedulerLogEntry;
    nvmlVgpuSchedulerLog_t *VgpuSchedulerLogPtr;
    nvmlVgpuSchedulerLog_t VgpuSchedulerLog;
    nvmlVgpuSchedulerSetState_t *VgpuSchedulerSetStatePtr;
    nvmlVgpuSchedulerSetState_t VgpuSchedulerSetState;
    nvmlVgpuTypeBar1Info_t *VgpuTypeBar1InfoPtr;
    nvmlVgpuTypeBar1Info_t VgpuTypeBar1Info;
    nvmlVgpuTypeId_t *VgpuTypeIdPtr;
    nvmlVgpuTypeId_t VgpuTypeId;
    nvmlVgpuVersion_t *VgpuVersionPtr;
    nvmlVgpuVersion_t VgpuVersion;
    nvmlVgpuVmCompatibility_t *VgpuVmCompatibilityPtr;
    nvmlVgpuVmCompatibility_t VgpuVmCompatibility;
    nvmlVgpuVmIdType_t *VgpuVmIdTypePtr;
    nvmlVgpuVmIdType_t VgpuVmIdType;
    nvmlViolationTime_t *ViolationTimePtr;
    nvmlViolationTime_t ViolationTime;
    nvmlWorkloadPowerProfileCurrentProfiles_t *WorkloadPowerProfileCurrentProfilesPtr;
    nvmlWorkloadPowerProfileCurrentProfiles_t WorkloadPowerProfileCurrentProfiles;
    nvmlWorkloadPowerProfileInfo_t *WorkloadPowerProfileInfoPtr;
    nvmlWorkloadPowerProfileInfo_t WorkloadPowerProfileInfo;
    nvmlWorkloadPowerProfileProfilesInfo_t *WorkloadPowerProfileProfilesInfoPtr;
    nvmlWorkloadPowerProfileProfilesInfo_t WorkloadPowerProfileProfilesInfo;
    nvmlWorkloadPowerProfileRequestedProfiles_t *WorkloadPowerProfileRequestedProfilesPtr;
    nvmlWorkloadPowerProfileRequestedProfiles_t WorkloadPowerProfileRequestedProfiles;
    nvmlWorkloadPowerProfileUpdateProfiles_v1_t *WorkloadPowerProfileUpdateProfiles_v1Ptr;
    nvmlWorkloadPowerProfileUpdateProfiles_v1_t WorkloadPowerProfileUpdateProfiles_v1;
    short *ShortPtr;
    short Short;
    unsigned char *UCharPtr;
    unsigned char UChar;
    unsigned int *UIntPtr;
    unsigned int UInt;
    unsigned long *ULongPtr;
    unsigned long ULong;
    unsigned long long *ULongLongPtr;
    unsigned long long ULongLong;
    unsigned short *UShortPtr;
    unsigned short UShort;
    const nvmlGpuInstancePlacement_t *ConstGpuInstancePlacementPtr;
    const char *ConstStr;
} simpleValue_t;

typedef enum injectionArg_enum
{
    INJECTION_CHAR = 0,
    INJECTION_CHAR_PTR = 1,
    INJECTION_DOUBLE = 2,
    INJECTION_DOUBLE_PTR = 3,
    INJECTION_INT = 4,
    INJECTION_INT_PTR = 5,
    INJECTION_LONG = 6,
    INJECTION_LONG_PTR = 7,
    INJECTION_LONG_LONG = 8,
    INJECTION_LONG_LONG_PTR = 9,
    INJECTION_ACCOUNTINGSTATS = 10,
    INJECTION_ACCOUNTINGSTATS_PTR = 11,
    INJECTION_AFFINITYSCOPE = 12,
    INJECTION_AFFINITYSCOPE_PTR = 13,
    INJECTION_BAR1MEMORY = 14,
    INJECTION_BAR1MEMORY_PTR = 15,
    INJECTION_BRANDTYPE = 16,
    INJECTION_BRANDTYPE_PTR = 17,
    INJECTION_BRIDGECHIPHIERARCHY = 18,
    INJECTION_BRIDGECHIPHIERARCHY_PTR = 19,
    INJECTION_BRIDGECHIPINFO = 20,
    INJECTION_BRIDGECHIPINFO_PTR = 21,
    INJECTION_BRIDGECHIPTYPE = 22,
    INJECTION_BRIDGECHIPTYPE_PTR = 23,
    INJECTION_BUSTYPE = 24,
    INJECTION_BUSTYPE_PTR = 25,
    INJECTION_C2CMODEINFO_V1 = 26,
    INJECTION_C2CMODEINFO_V1_PTR = 27,
    INJECTION_CLKMONFAULTINFO = 28,
    INJECTION_CLKMONFAULTINFO_PTR = 29,
    INJECTION_CLKMONSTATUS = 30,
    INJECTION_CLKMONSTATUS_PTR = 31,
    INJECTION_CLOCKID = 32,
    INJECTION_CLOCKID_PTR = 33,
    INJECTION_CLOCKLIMITID = 34,
    INJECTION_CLOCKLIMITID_PTR = 35,
    INJECTION_CLOCKOFFSET = 36,
    INJECTION_CLOCKOFFSET_PTR = 37,
    INJECTION_CLOCKTYPE = 38,
    INJECTION_CLOCKTYPE_PTR = 39,
    INJECTION_COMPUTEINSTANCEINFO = 40,
    INJECTION_COMPUTEINSTANCEINFO_PTR = 41,
    INJECTION_COMPUTEINSTANCEPLACEMENT = 42,
    INJECTION_COMPUTEINSTANCEPLACEMENT_PTR = 43,
    INJECTION_COMPUTEINSTANCEPROFILEINFO = 44,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_PTR = 45,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V2 = 46,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V2_PTR = 47,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V3 = 48,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V3_PTR = 49,
    INJECTION_COMPUTEINSTANCE = 50,
    INJECTION_COMPUTEINSTANCE_PTR = 51,
    INJECTION_COMPUTEMODE = 52,
    INJECTION_COMPUTEMODE_PTR = 53,
    INJECTION_CONFCOMPUTEGETKEYROTATIONTHRESHOLDINFO_V1 = 54,
    INJECTION_CONFCOMPUTEGETKEYROTATIONTHRESHOLDINFO_V1_PTR = 55,
    INJECTION_CONFCOMPUTEGPUATTESTATIONREPORT = 56,
    INJECTION_CONFCOMPUTEGPUATTESTATIONREPORT_PTR = 57,
    INJECTION_CONFCOMPUTEGPUCERTIFICATE = 58,
    INJECTION_CONFCOMPUTEGPUCERTIFICATE_PTR = 59,
    INJECTION_CONFCOMPUTEMEMSIZEINFO = 60,
    INJECTION_CONFCOMPUTEMEMSIZEINFO_PTR = 61,
    INJECTION_CONFCOMPUTESETKEYROTATIONTHRESHOLDINFO_V1 = 62,
    INJECTION_CONFCOMPUTESETKEYROTATIONTHRESHOLDINFO_V1_PTR = 63,
    INJECTION_CONFCOMPUTESYSTEMCAPS = 64,
    INJECTION_CONFCOMPUTESYSTEMCAPS_PTR = 65,
    INJECTION_CONFCOMPUTESYSTEMSTATE = 66,
    INJECTION_CONFCOMPUTESYSTEMSTATE_PTR = 67,
    INJECTION_COOLERCONTROL = 68,
    INJECTION_COOLERCONTROL_PTR = 69,
    INJECTION_COOLERINFO = 70,
    INJECTION_COOLERINFO_PTR = 71,
    INJECTION_COOLERTARGET = 72,
    INJECTION_COOLERTARGET_PTR = 73,
    INJECTION_DETACHGPUSTATE = 74,
    INJECTION_DETACHGPUSTATE_PTR = 75,
    INJECTION_DEVICEARCHITECTURE = 76,
    INJECTION_DEVICEARCHITECTURE_PTR = 77,
    INJECTION_DEVICEATTRIBUTES = 78,
    INJECTION_DEVICEATTRIBUTES_PTR = 79,
    INJECTION_DEVICECAPABILITIES = 80,
    INJECTION_DEVICECAPABILITIES_PTR = 81,
    INJECTION_DEVICECURRENTCLOCKFREQS = 82,
    INJECTION_DEVICECURRENTCLOCKFREQS_PTR = 83,
    INJECTION_DEVICEGPURECOVERYACTION = 84,
    INJECTION_DEVICEGPURECOVERYACTION_PTR = 85,
    INJECTION_DEVICEPERFMODES = 86,
    INJECTION_DEVICEPERFMODES_PTR = 87,
    INJECTION_DEVICEVGPUCAPABILITY = 88,
    INJECTION_DEVICEVGPUCAPABILITY_PTR = 89,
    INJECTION_DEVICE = 90,
    INJECTION_DEVICE_PTR = 91,
    INJECTION_DRIVERMODEL = 92,
    INJECTION_DRIVERMODEL_PTR = 93,
    INJECTION_ECCCOUNTERTYPE = 94,
    INJECTION_ECCCOUNTERTYPE_PTR = 95,
    INJECTION_ECCERRORCOUNTS = 96,
    INJECTION_ECCERRORCOUNTS_PTR = 97,
    INJECTION_ECCSRAMERRORSTATUS = 98,
    INJECTION_ECCSRAMERRORSTATUS_PTR = 99,
    INJECTION_ENABLESTATE = 100,
    INJECTION_ENABLESTATE_PTR = 101,
    INJECTION_ENCODERSESSIONINFO = 102,
    INJECTION_ENCODERSESSIONINFO_PTR = 103,
    INJECTION_ENCODERTYPE = 104,
    INJECTION_ENCODERTYPE_PTR = 105,
    INJECTION_EVENTDATA = 106,
    INJECTION_EVENTDATA_PTR = 107,
    INJECTION_EVENTSET = 108,
    INJECTION_EVENTSET_PTR = 109,
    INJECTION_EXCLUDEDDEVICEINFO = 110,
    INJECTION_EXCLUDEDDEVICEINFO_PTR = 111,
    INJECTION_FBCSESSIONINFO = 112,
    INJECTION_FBCSESSIONINFO_PTR = 113,
    INJECTION_FBCSESSIONTYPE = 114,
    INJECTION_FBCSESSIONTYPE_PTR = 115,
    INJECTION_FBCSTATS = 116,
    INJECTION_FBCSTATS_PTR = 117,
    INJECTION_FANCONTROLPOLICY = 118,
    INJECTION_FANCONTROLPOLICY_PTR = 119,
    INJECTION_FANSPEEDINFO = 120,
    INJECTION_FANSPEEDINFO_PTR = 121,
    INJECTION_FANSTATE = 122,
    INJECTION_FANSTATE_PTR = 123,
    INJECTION_FIELDVALUE = 124,
    INJECTION_FIELDVALUE_PTR = 125,
    INJECTION_GPMMETRICID = 126,
    INJECTION_GPMMETRICID_PTR = 127,
    INJECTION_GPMMETRIC = 128,
    INJECTION_GPMMETRIC_PTR = 129,
    INJECTION_GPMMETRICSGET = 130,
    INJECTION_GPMMETRICSGET_PTR = 131,
    INJECTION_GPMSAMPLE = 132,
    INJECTION_GPMSAMPLE_PTR = 133,
    INJECTION_GPMSUPPORT = 134,
    INJECTION_GPMSUPPORT_PTR = 135,
    INJECTION_GPUDYNAMICPSTATESINFO = 136,
    INJECTION_GPUDYNAMICPSTATESINFO_PTR = 137,
    INJECTION_GPUFABRICINFOV = 138,
    INJECTION_GPUFABRICINFOV_PTR = 139,
    INJECTION_GPUFABRICINFO = 140,
    INJECTION_GPUFABRICINFO_PTR = 141,
    INJECTION_GPUFABRICSTATE = 142,
    INJECTION_GPUFABRICSTATE_PTR = 143,
    INJECTION_GPUINSTANCEINFO = 144,
    INJECTION_GPUINSTANCEINFO_PTR = 145,
    INJECTION_GPUINSTANCEPLACEMENT = 146,
    INJECTION_GPUINSTANCEPLACEMENT_PTR = 147,
    INJECTION_GPUINSTANCEPROFILEINFO = 148,
    INJECTION_GPUINSTANCEPROFILEINFO_PTR = 149,
    INJECTION_GPUINSTANCEPROFILEINFO_V2 = 150,
    INJECTION_GPUINSTANCEPROFILEINFO_V2_PTR = 151,
    INJECTION_GPUINSTANCEPROFILEINFO_V3 = 152,
    INJECTION_GPUINSTANCEPROFILEINFO_V3_PTR = 153,
    INJECTION_GPUINSTANCE = 154,
    INJECTION_GPUINSTANCE_PTR = 155,
    INJECTION_GPUOPERATIONMODE = 156,
    INJECTION_GPUOPERATIONMODE_PTR = 157,
    INJECTION_GPUP2PCAPSINDEX = 158,
    INJECTION_GPUP2PCAPSINDEX_PTR = 159,
    INJECTION_GPUP2PSTATUS = 160,
    INJECTION_GPUP2PSTATUS_PTR = 161,
    INJECTION_GPUTHERMALSETTINGS = 162,
    INJECTION_GPUTHERMALSETTINGS_PTR = 163,
    INJECTION_GPUTOPOLOGYLEVEL = 164,
    INJECTION_GPUTOPOLOGYLEVEL_PTR = 165,
    INJECTION_GPUUTILIZATIONDOMAINID = 166,
    INJECTION_GPUUTILIZATIONDOMAINID_PTR = 167,
    INJECTION_GPUVIRTUALIZATIONMODE = 168,
    INJECTION_GPUVIRTUALIZATIONMODE_PTR = 169,
    INJECTION_GRIDLICENSABLEFEATURE = 170,
    INJECTION_GRIDLICENSABLEFEATURE_PTR = 171,
    INJECTION_GRIDLICENSABLEFEATURES = 172,
    INJECTION_GRIDLICENSABLEFEATURES_PTR = 173,
    INJECTION_GRIDLICENSEEXPIRY = 174,
    INJECTION_GRIDLICENSEEXPIRY_PTR = 175,
    INJECTION_GRIDLICENSEFEATURECODE = 176,
    INJECTION_GRIDLICENSEFEATURECODE_PTR = 177,
    INJECTION_HOSTVGPUMODE = 178,
    INJECTION_HOSTVGPUMODE_PTR = 179,
    INJECTION_HWBCENTRY = 180,
    INJECTION_HWBCENTRY_PTR = 181,
    INJECTION_INFOROMOBJECT = 182,
    INJECTION_INFOROMOBJECT_PTR = 183,
    INJECTION_INTNVLINKDEVICETYPE = 184,
    INJECTION_INTNVLINKDEVICETYPE_PTR = 185,
    INJECTION_LEDCOLOR = 186,
    INJECTION_LEDCOLOR_PTR = 187,
    INJECTION_LEDSTATE = 188,
    INJECTION_LEDSTATE_PTR = 189,
    INJECTION_MARGINTEMPERATURE = 190,
    INJECTION_MARGINTEMPERATURE_PTR = 191,
    INJECTION_MASK255 = 192,
    INJECTION_MASK255_PTR = 193,
    INJECTION_MEMORYERRORTYPE = 194,
    INJECTION_MEMORYERRORTYPE_PTR = 195,
    INJECTION_MEMORYLOCATION = 196,
    INJECTION_MEMORYLOCATION_PTR = 197,
    INJECTION_MEMORY = 198,
    INJECTION_MEMORY_PTR = 199,
    INJECTION_MEMORY_V2 = 200,
    INJECTION_MEMORY_V2_PTR = 201,
    INJECTION_NVLINKCAPABILITY = 202,
    INJECTION_NVLINKCAPABILITY_PTR = 203,
    INJECTION_NVLINKERRORCOUNTER = 204,
    INJECTION_NVLINKERRORCOUNTER_PTR = 205,
    INJECTION_NVLINKPOWERTHRES = 206,
    INJECTION_NVLINKPOWERTHRES_PTR = 207,
    INJECTION_NVLINKUTILIZATIONCONTROL = 208,
    INJECTION_NVLINKUTILIZATIONCONTROL_PTR = 209,
    INJECTION_NVLINKUTILIZATIONCOUNTPKTTYPES = 210,
    INJECTION_NVLINKUTILIZATIONCOUNTPKTTYPES_PTR = 211,
    INJECTION_NVLINKUTILIZATIONCOUNTUNITS = 212,
    INJECTION_NVLINKUTILIZATIONCOUNTUNITS_PTR = 213,
    INJECTION_NVLINKVERSION = 214,
    INJECTION_NVLINKVERSION_PTR = 215,
    INJECTION_PSUINFO = 216,
    INJECTION_PSUINFO_PTR = 217,
    INJECTION_PAGERETIREMENTCAUSE = 218,
    INJECTION_PAGERETIREMENTCAUSE_PTR = 219,
    INJECTION_PCIINFOEXT = 220,
    INJECTION_PCIINFOEXT_PTR = 221,
    INJECTION_PCIINFO = 222,
    INJECTION_PCIINFO_PTR = 223,
    INJECTION_PCIELINKSTATE = 224,
    INJECTION_PCIELINKSTATE_PTR = 225,
    INJECTION_PCIEUTILCOUNTER = 226,
    INJECTION_PCIEUTILCOUNTER_PTR = 227,
    INJECTION_PERFPOLICYTYPE = 228,
    INJECTION_PERFPOLICYTYPE_PTR = 229,
    INJECTION_PLATFORMINFO = 230,
    INJECTION_PLATFORMINFO_PTR = 231,
    INJECTION_PLATFORMINFO_V1 = 232,
    INJECTION_PLATFORMINFO_V1_PTR = 233,
    INJECTION_POWERPROFILEOPERATION = 234,
    INJECTION_POWERPROFILEOPERATION_PTR = 235,
    INJECTION_POWERPROFILETYPE = 236,
    INJECTION_POWERPROFILETYPE_PTR = 237,
    INJECTION_POWERSCOPETYPE = 238,
    INJECTION_POWERSCOPETYPE_PTR = 239,
    INJECTION_POWERSOURCE = 240,
    INJECTION_POWERSOURCE_PTR = 241,
    INJECTION_POWERVALUE_V2 = 242,
    INJECTION_POWERVALUE_V2_PTR = 243,
    INJECTION_PROCESSDETAILLIST = 244,
    INJECTION_PROCESSDETAILLIST_PTR = 245,
    INJECTION_PROCESSDETAIL_V1 = 246,
    INJECTION_PROCESSDETAIL_V1_PTR = 247,
    INJECTION_PROCESSINFO = 248,
    INJECTION_PROCESSINFO_PTR = 249,
    INJECTION_PROCESSINFO_V1 = 250,
    INJECTION_PROCESSINFO_V1_PTR = 251,
    INJECTION_PROCESSUTILIZATIONINFO_V1 = 252,
    INJECTION_PROCESSUTILIZATIONINFO_V1_PTR = 253,
    INJECTION_PROCESSUTILIZATIONSAMPLE = 254,
    INJECTION_PROCESSUTILIZATIONSAMPLE_PTR = 255,
    INJECTION_PROCESSESUTILIZATIONINFO = 256,
    INJECTION_PROCESSESUTILIZATIONINFO_PTR = 257,
    INJECTION_PSTATES = 258,
    INJECTION_PSTATES_PTR = 259,
    INJECTION_RESTRICTEDAPI = 260,
    INJECTION_RESTRICTEDAPI_PTR = 261,
    INJECTION_RETURN = 262,
    INJECTION_RETURN_PTR = 263,
    INJECTION_ROWREMAPPERHISTOGRAMVALUES = 264,
    INJECTION_ROWREMAPPERHISTOGRAMVALUES_PTR = 265,
    INJECTION_SAMPLE = 266,
    INJECTION_SAMPLE_PTR = 267,
    INJECTION_SAMPLINGTYPE = 268,
    INJECTION_SAMPLINGTYPE_PTR = 269,
    INJECTION_SYSTEMCONFCOMPUTESETTINGS = 270,
    INJECTION_SYSTEMCONFCOMPUTESETTINGS_PTR = 271,
    INJECTION_SYSTEMDRIVERBRANCHINFO = 272,
    INJECTION_SYSTEMDRIVERBRANCHINFO_PTR = 273,
    INJECTION_SYSTEMEVENTDATA_V1 = 274,
    INJECTION_SYSTEMEVENTDATA_V1_PTR = 275,
    INJECTION_SYSTEMEVENTSETCREATEREQUEST = 276,
    INJECTION_SYSTEMEVENTSETCREATEREQUEST_PTR = 277,
    INJECTION_SYSTEMEVENTSETFREEREQUEST = 278,
    INJECTION_SYSTEMEVENTSETFREEREQUEST_PTR = 279,
    INJECTION_SYSTEMEVENTSETWAITREQUEST = 280,
    INJECTION_SYSTEMEVENTSETWAITREQUEST_PTR = 281,
    INJECTION_SYSTEMREGISTEREVENTREQUEST = 282,
    INJECTION_SYSTEMREGISTEREVENTREQUEST_PTR = 283,
    INJECTION_TEMPERATURESENSORS = 284,
    INJECTION_TEMPERATURESENSORS_PTR = 285,
    INJECTION_TEMPERATURETHRESHOLDS = 286,
    INJECTION_TEMPERATURETHRESHOLDS_PTR = 287,
    INJECTION_TEMPERATURE = 288,
    INJECTION_TEMPERATURE_PTR = 289,
    INJECTION_THERMALCONTROLLER = 290,
    INJECTION_THERMALCONTROLLER_PTR = 291,
    INJECTION_THERMALTARGET = 292,
    INJECTION_THERMALTARGET_PTR = 293,
    INJECTION_UNITFANINFO = 294,
    INJECTION_UNITFANINFO_PTR = 295,
    INJECTION_UNITFANSPEEDS = 296,
    INJECTION_UNITFANSPEEDS_PTR = 297,
    INJECTION_UNITINFO = 298,
    INJECTION_UNITINFO_PTR = 299,
    INJECTION_UNIT = 300,
    INJECTION_UNIT_PTR = 301,
    INJECTION_UTILIZATION = 302,
    INJECTION_UTILIZATION_PTR = 303,
    INJECTION_VALUETYPE = 304,
    INJECTION_VALUETYPE_PTR = 305,
    INJECTION_VGPUCAPABILITY = 306,
    INJECTION_VGPUCAPABILITY_PTR = 307,
    INJECTION_VGPUDRIVERCAPABILITY = 308,
    INJECTION_VGPUDRIVERCAPABILITY_PTR = 309,
    INJECTION_VGPUGUESTINFOSTATE = 310,
    INJECTION_VGPUGUESTINFOSTATE_PTR = 311,
    INJECTION_VGPUHETEROGENEOUSMODE = 312,
    INJECTION_VGPUHETEROGENEOUSMODE_PTR = 313,
    INJECTION_VGPUINSTANCEUTILIZATIONINFO_V1 = 314,
    INJECTION_VGPUINSTANCEUTILIZATIONINFO_V1_PTR = 315,
    INJECTION_VGPUINSTANCEUTILIZATIONSAMPLE = 316,
    INJECTION_VGPUINSTANCEUTILIZATIONSAMPLE_PTR = 317,
    INJECTION_VGPUINSTANCE = 318,
    INJECTION_VGPUINSTANCE_PTR = 319,
    INJECTION_VGPUINSTANCESUTILIZATIONINFO = 320,
    INJECTION_VGPUINSTANCESUTILIZATIONINFO_PTR = 321,
    INJECTION_VGPULICENSEEXPIRY = 322,
    INJECTION_VGPULICENSEEXPIRY_PTR = 323,
    INJECTION_VGPULICENSEINFO = 324,
    INJECTION_VGPULICENSEINFO_PTR = 325,
    INJECTION_VGPUMETADATA = 326,
    INJECTION_VGPUMETADATA_PTR = 327,
    INJECTION_VGPUPGPUCOMPATIBILITYLIMITCODE = 328,
    INJECTION_VGPUPGPUCOMPATIBILITYLIMITCODE_PTR = 329,
    INJECTION_VGPUPGPUCOMPATIBILITY = 330,
    INJECTION_VGPUPGPUCOMPATIBILITY_PTR = 331,
    INJECTION_VGPUPGPUMETADATA = 332,
    INJECTION_VGPUPGPUMETADATA_PTR = 333,
    INJECTION_VGPUPLACEMENTID = 334,
    INJECTION_VGPUPLACEMENTID_PTR = 335,
    INJECTION_VGPUPLACEMENTLIST = 336,
    INJECTION_VGPUPLACEMENTLIST_PTR = 337,
    INJECTION_VGPUPLACEMENTLIST_V1 = 338,
    INJECTION_VGPUPLACEMENTLIST_V1_PTR = 339,
    INJECTION_VGPUPROCESSUTILIZATIONINFO_V1 = 340,
    INJECTION_VGPUPROCESSUTILIZATIONINFO_V1_PTR = 341,
    INJECTION_VGPUPROCESSUTILIZATIONSAMPLE = 342,
    INJECTION_VGPUPROCESSUTILIZATIONSAMPLE_PTR = 343,
    INJECTION_VGPUPROCESSESUTILIZATIONINFO = 344,
    INJECTION_VGPUPROCESSESUTILIZATIONINFO_PTR = 345,
    INJECTION_VGPURUNTIMESTATE = 346,
    INJECTION_VGPURUNTIMESTATE_PTR = 347,
    INJECTION_VGPUSCHEDULERCAPABILITIES = 348,
    INJECTION_VGPUSCHEDULERCAPABILITIES_PTR = 349,
    INJECTION_VGPUSCHEDULERGETSTATE = 350,
    INJECTION_VGPUSCHEDULERGETSTATE_PTR = 351,
    INJECTION_VGPUSCHEDULERLOGENTRY = 352,
    INJECTION_VGPUSCHEDULERLOGENTRY_PTR = 353,
    INJECTION_VGPUSCHEDULERLOG = 354,
    INJECTION_VGPUSCHEDULERLOG_PTR = 355,
    INJECTION_VGPUSCHEDULERSETSTATE = 356,
    INJECTION_VGPUSCHEDULERSETSTATE_PTR = 357,
    INJECTION_VGPUTYPEBAR1INFO = 358,
    INJECTION_VGPUTYPEBAR1INFO_PTR = 359,
    INJECTION_VGPUTYPEID = 360,
    INJECTION_VGPUTYPEID_PTR = 361,
    INJECTION_VGPUVERSION = 362,
    INJECTION_VGPUVERSION_PTR = 363,
    INJECTION_VGPUVMCOMPATIBILITY = 364,
    INJECTION_VGPUVMCOMPATIBILITY_PTR = 365,
    INJECTION_VGPUVMIDTYPE = 366,
    INJECTION_VGPUVMIDTYPE_PTR = 367,
    INJECTION_VIOLATIONTIME = 368,
    INJECTION_VIOLATIONTIME_PTR = 369,
    INJECTION_WORKLOADPOWERPROFILECURRENTPROFILES = 370,
    INJECTION_WORKLOADPOWERPROFILECURRENTPROFILES_PTR = 371,
    INJECTION_WORKLOADPOWERPROFILEINFO = 372,
    INJECTION_WORKLOADPOWERPROFILEINFO_PTR = 373,
    INJECTION_WORKLOADPOWERPROFILEPROFILESINFO = 374,
    INJECTION_WORKLOADPOWERPROFILEPROFILESINFO_PTR = 375,
    INJECTION_WORKLOADPOWERPROFILEREQUESTEDPROFILES = 376,
    INJECTION_WORKLOADPOWERPROFILEREQUESTEDPROFILES_PTR = 377,
    INJECTION_WORKLOADPOWERPROFILEUPDATEPROFILES_V1 = 378,
    INJECTION_WORKLOADPOWERPROFILEUPDATEPROFILES_V1_PTR = 379,
    INJECTION_SHORT = 380,
    INJECTION_SHORT_PTR = 381,
    INJECTION_UCHAR = 382,
    INJECTION_UCHAR_PTR = 383,
    INJECTION_UINT = 384,
    INJECTION_UINT_PTR = 385,
    INJECTION_ULONG = 386,
    INJECTION_ULONG_PTR = 387,
    INJECTION_ULONG_LONG = 388,
    INJECTION_ULONG_LONG_PTR = 389,
    INJECTION_USHORT = 390,
    INJECTION_USHORT_PTR = 391,
    INJECTION_STRING = 392,
    INJECTION_CONST_GPUINSTANCEPLACEMENT = 393,
    INJECTION_CONST_GPUINSTANCEPLACEMENT_PTR = 394,
    INJECTION_CONST_CHAR = 395,
    INJECTION_CONST_CHAR_PTR = 396,
    InjectionArgCount
} injectionArgType_t;

typedef struct
{
    simpleValue_t value;
    injectionArgType_t type;
} injectNvmlVal_t;

