/*
 * Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: This code is auto-generated by generate_nvml_stubs.py
 * DO NOT EDIT MANUALLY
 */


// clang-format off
#pragma once

#include <nvml.h>
// The following snippet is generated from write_injection_structs_header
typedef union
{
    char c;
    char *str;
    const char *const_str;
    const nvmlGpuInstancePlacement_t *cnPtr;
    int i;
    int *iPtr;
    nvmlAccountingStats_t accountingStats;
    nvmlAccountingStats_t *accountingStatsPtr;
    nvmlBAR1Memory_t bar1Memory;
    nvmlBAR1Memory_t *bar1MemoryPtr;
    nvmlBrandType_t brandType;
    nvmlBrandType_t *brandTypePtr;
    nvmlBridgeChipHierarchy_t bridgeChipHierarchy;
    nvmlBridgeChipHierarchy_t *bridgeChipHierarchyPtr;
    nvmlClockId_t clockId;
    nvmlClockType_t clockType;
    nvmlComputeInstanceInfo_t computeInstanceInfo;
    nvmlComputeInstanceInfo_t *computeInstanceInfoPtr;
    nvmlComputeInstanceProfileInfo_t computeInstanceProfileInfo;
    nvmlComputeInstanceProfileInfo_t *computeInstanceProfileInfoPtr;
    nvmlComputeInstanceProfileInfo_v2_t computeInstanceProfileInfo_v2;
    nvmlComputeInstanceProfileInfo_v2_t *computeInstanceProfileInfo_v2Ptr;
    nvmlComputeInstance_t computeInstance;
    nvmlComputeInstance_t *computeInstancePtr;
    nvmlComputeMode_t computeMode;
    nvmlComputeMode_t *computeModePtr;
    nvmlConfComputeSystemState_t confComputeSystemState;
    nvmlConfComputeSystemState_t *confComputeSystemStatePtr;
    nvmlDetachGpuState_t detachGpuState;
    nvmlDeviceAttributes_t deviceAttributes;
    nvmlDeviceAttributes_t *deviceAttributesPtr;
    nvmlDevice_t device;
    nvmlDevice_t *devicePtr;
    nvmlDriverModel_t driverModel;
    nvmlDriverModel_t *driverModelPtr;
    nvmlEccCounterType_t eccCounterType;
    nvmlEccErrorCounts_t eccErrorCounts;
    nvmlEccErrorCounts_t *eccErrorCountsPtr;
    nvmlEnableState_t enableState;
    nvmlEnableState_t *enableStatePtr;
    nvmlEncoderSessionInfo_t encoderSessionInfo;
    nvmlEncoderSessionInfo_t *encoderSessionInfoPtr;
    nvmlEncoderType_t encoderType;
    nvmlEventData_t eventData;
    nvmlEventData_t *eventDataPtr;
    nvmlEventSet_t eventSet;
    nvmlEventSet_t *eventSetPtr;
    nvmlExcludedDeviceInfo_t excludedDeviceInfo;
    nvmlExcludedDeviceInfo_t *excludedDeviceInfoPtr;
    nvmlFBCSessionInfo_t fBCSessionInfo;
    nvmlFBCSessionInfo_t *fBCSessionInfoPtr;
    nvmlFBCStats_t fBCStats;
    nvmlFBCStats_t *fBCStatsPtr;
    nvmlFieldValue_t fieldValue;
    nvmlFieldValue_t *fieldValuePtr;
    nvmlGpmMetricsGet_t gpmMetricsGet;
    nvmlGpmMetricsGet_t *gpmMetricsGetPtr;
    nvmlGpmSample_t gpmSample;
    nvmlGpmSample_t *gpmSamplePtr;
    nvmlGpmSupport_t gpmSupport;
    nvmlGpmSupport_t *gpmSupportPtr;
    nvmlGpuDynamicPstatesInfo_t gpuDynamicPstatesInfo;
    nvmlGpuDynamicPstatesInfo_t *gpuDynamicPstatesInfoPtr;
    nvmlGpuInstanceInfo_t gpuInstanceInfo;
    nvmlGpuInstanceInfo_t *gpuInstanceInfoPtr;
    nvmlGpuInstancePlacement_t gpuInstancePlacement;
    nvmlGpuInstancePlacement_t *gpuInstancePlacementPtr;
    nvmlGpuInstanceProfileInfo_t gpuInstanceProfileInfo;
    nvmlGpuInstanceProfileInfo_t *gpuInstanceProfileInfoPtr;
    nvmlGpuInstanceProfileInfo_v2_t gpuInstanceProfileInfo_v2;
    nvmlGpuInstanceProfileInfo_v2_t *gpuInstanceProfileInfo_v2Ptr;
    nvmlGpuInstance_t gpuInstance;
    nvmlGpuInstance_t *gpuInstancePtr;
    nvmlGpuOperationMode_t gpuOperationMode;
    nvmlGpuOperationMode_t *gpuOperationModePtr;
    nvmlGpuP2PCapsIndex_t gpuP2PCapsIndex;
    nvmlGpuP2PStatus_t gpuP2PStatus;
    nvmlGpuP2PStatus_t *gpuP2PStatusPtr;
    nvmlGpuThermalSettings_t gpuThermalSettings;
    nvmlGpuThermalSettings_t *gpuThermalSettingsPtr;
    nvmlGpuTopologyLevel_t gpuTopologyLevel;
    nvmlGpuTopologyLevel_t *gpuTopologyLevelPtr;
    nvmlGpuVirtualizationMode_t gpuVirtualizationMode;
    nvmlGpuVirtualizationMode_t *gpuVirtualizationModePtr;
    nvmlGridLicensableFeatures_t gridLicensableFeatures;
    nvmlGridLicensableFeatures_t *gridLicensableFeaturesPtr;
    nvmlHostVgpuMode_t hostVgpuMode;
    nvmlHostVgpuMode_t *hostVgpuModePtr;
    nvmlHwbcEntry_t hwbcEntry;
    nvmlHwbcEntry_t *hwbcEntryPtr;
    nvmlInforomObject_t inforomObject;
    nvmlIntNvLinkDeviceType_t intNvLinkDeviceType;
    nvmlIntNvLinkDeviceType_t *intNvLinkDeviceTypePtr;
    nvmlLedColor_t ledColor;
    nvmlLedState_t ledState;
    nvmlLedState_t *ledStatePtr;
    nvmlMemoryErrorType_t memoryErrorType;
    nvmlMemoryLocation_t memoryLocation;
    nvmlMemory_t memory;
    nvmlMemory_t *memoryPtr;
    nvmlMemory_v2_t memory_v2;
    nvmlMemory_v2_t *memory_v2Ptr;
    nvmlNvLinkCapability_t nvLinkCapability;
    nvmlNvLinkErrorCounter_t nvLinkErrorCounter;
    nvmlNvLinkUtilizationControl_t nvLinkUtilizationControl;
    nvmlNvLinkUtilizationControl_t *nvLinkUtilizationControlPtr;
    nvmlPSUInfo_t pSUInfo;
    nvmlPSUInfo_t *pSUInfoPtr;
    nvmlPageRetirementCause_t pageRetirementCause;
    nvmlPciInfo_t pciInfo;
    nvmlPciInfo_t *pciInfoPtr;
    nvmlPcieLinkState_t pcieLinkState;
    nvmlPcieUtilCounter_t pcieUtilCounter;
    nvmlPerfPolicyType_t perfPolicyType;
    nvmlProcessInfo_t processInfo;
    nvmlProcessInfo_t *processInfoPtr;
    nvmlProcessInfo_v1_t processInfo_v1;
    nvmlProcessInfo_v1_t *processInfo_v1Ptr;
    nvmlProcessInfo_v2_t processInfo_v2;
    nvmlProcessInfo_v2_t *processInfo_v2Ptr;
    nvmlProcessUtilizationSample_t processUtilizationSample;
    nvmlProcessUtilizationSample_t *processUtilizationSamplePtr;
    nvmlPstates_t pstates;
    nvmlPstates_t *pstatesPtr;
    nvmlRestrictedAPI_t restrictedAPI;
    nvmlReturn_t nvmlReturn;
    nvmlReturn_t *nvmlReturnPtr;
    nvmlRowRemapperHistogramValues_t rowRemapperHistogramValues;
    nvmlRowRemapperHistogramValues_t *rowRemapperHistogramValuesPtr;
    nvmlSample_t sample;
    nvmlSample_t *samplePtr;
    nvmlSamplingType_t samplingType;
    nvmlTemperatureSensors_t temperatureSensors;
    nvmlTemperatureThresholds_t temperatureThresholds;
    nvmlUnitFanSpeeds_t unitFanSpeeds;
    nvmlUnitFanSpeeds_t *unitFanSpeedsPtr;
    nvmlUnitInfo_t unitInfo;
    nvmlUnitInfo_t *unitInfoPtr;
    nvmlUnit_t unit;
    nvmlUnit_t *unitPtr;
    nvmlUtilization_t utilization;
    nvmlUtilization_t *utilizationPtr;
    nvmlValueType_t valueType;
    nvmlValueType_t *valueTypePtr;
    nvmlVgpuCapability_t vgpuCapability;
    nvmlVgpuInstanceUtilizationSample_t vgpuInstanceUtilizationSample;
    nvmlVgpuInstanceUtilizationSample_t *vgpuInstanceUtilizationSamplePtr;
    nvmlVgpuLicenseInfo_t vgpuLicenseInfo;
    nvmlVgpuLicenseInfo_t *vgpuLicenseInfoPtr;
    nvmlVgpuMetadata_t vgpuMetadata;
    nvmlVgpuMetadata_t *vgpuMetadataPtr;
    nvmlVgpuPgpuCompatibility_t vgpuPgpuCompatibility;
    nvmlVgpuPgpuCompatibility_t *vgpuPgpuCompatibilityPtr;
    nvmlVgpuPgpuMetadata_t vgpuPgpuMetadata;
    nvmlVgpuPgpuMetadata_t *vgpuPgpuMetadataPtr;
    nvmlVgpuProcessUtilizationSample_t vgpuProcessUtilizationSample;
    nvmlVgpuProcessUtilizationSample_t *vgpuProcessUtilizationSamplePtr;
    nvmlVgpuVersion_t vgpuVersion;
    nvmlVgpuVersion_t *vgpuVersionPtr;
    nvmlVgpuVmIdType_t vgpuVmIdType;
    nvmlVgpuVmIdType_t *vgpuVmIdTypePtr;
    nvmlViolationTime_t violationTime;
    nvmlViolationTime_t *violationTimePtr;
    unsigned int ui;
    unsigned int *uiPtr;
    unsigned long ul;
    unsigned long *ulPtr;
    unsigned long long ull;
    unsigned long long *ullPtr;
} simpleValue_t;

typedef enum injectionArg_enum
{
    INJECTION_CHAR                                 = 0,
    INJECTION_CHAR_PTR                             = 1,
    INJECTION_CONST_CHAR_PTR                       = 2,
    INJECTION_CONST_NVMLGPUINSTANCEPLACEMENT_T_PTR = 3,
    INJECTION_INT                                  = 4,
    INJECTION_INT_PTR                              = 5,
    INJECTION_ACCOUNTINGSTATS                      = 6,
    INJECTION_ACCOUNTINGSTATS_PTR                  = 7,
    INJECTION_BAR1MEMORY                           = 8,
    INJECTION_BAR1MEMORY_PTR                       = 9,
    INJECTION_BRANDTYPE                            = 10,
    INJECTION_BRANDTYPE_PTR                        = 11,
    INJECTION_BRIDGECHIPHIERARCHY                  = 12,
    INJECTION_BRIDGECHIPHIERARCHY_PTR              = 13,
    INJECTION_CLOCKID                              = 14,
    INJECTION_CLOCKTYPE                            = 15,
    INJECTION_COMPUTEINSTANCEINFO                  = 16,
    INJECTION_COMPUTEINSTANCEINFO_PTR              = 17,
    INJECTION_COMPUTEINSTANCEPROFILEINFO           = 18,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_PTR       = 19,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V2        = 20,
    INJECTION_COMPUTEINSTANCEPROFILEINFO_V2_PTR    = 21,
    INJECTION_COMPUTEINSTANCE                      = 22,
    INJECTION_COMPUTEINSTANCE_PTR                  = 23,
    INJECTION_COMPUTEMODE                          = 24,
    INJECTION_COMPUTEMODE_PTR                      = 25,
    INJECTION_CONFCOMPUTESYSTEMSTATE               = 26,
    INJECTION_CONFCOMPUTESYSTEMSTATE_PTR           = 27,
    INJECTION_DETACHGPUSTATE                       = 28,
    INJECTION_DEVICEATTRIBUTES                     = 29,
    INJECTION_DEVICEATTRIBUTES_PTR                 = 30,
    INJECTION_DEVICE                               = 31,
    INJECTION_DEVICE_PTR                           = 32,
    INJECTION_DRIVERMODEL                          = 33,
    INJECTION_DRIVERMODEL_PTR                      = 34,
    INJECTION_ECCCOUNTERTYPE                       = 35,
    INJECTION_ECCERRORCOUNTS                       = 36,
    INJECTION_ECCERRORCOUNTS_PTR                   = 37,
    INJECTION_ENABLESTATE                          = 38,
    INJECTION_ENABLESTATE_PTR                      = 39,
    INJECTION_ENCODERSESSIONINFO                   = 40,
    INJECTION_ENCODERSESSIONINFO_PTR               = 41,
    INJECTION_ENCODERTYPE                          = 42,
    INJECTION_EVENTDATA                            = 43,
    INJECTION_EVENTDATA_PTR                        = 44,
    INJECTION_EVENTSET                             = 45,
    INJECTION_EVENTSET_PTR                         = 46,
    INJECTION_EXCLUDEDDEVICEINFO                   = 47,
    INJECTION_EXCLUDEDDEVICEINFO_PTR               = 48,
    INJECTION_FBCSESSIONINFO                       = 49,
    INJECTION_FBCSESSIONINFO_PTR                   = 50,
    INJECTION_FBCSTATS                             = 51,
    INJECTION_FBCSTATS_PTR                         = 52,
    INJECTION_FIELDVALUE                           = 53,
    INJECTION_FIELDVALUE_PTR                       = 54,
    INJECTION_GPMMETRICSGET                        = 55,
    INJECTION_GPMMETRICSGET_PTR                    = 56,
    INJECTION_GPMSAMPLE                            = 57,
    INJECTION_GPMSAMPLE_PTR                        = 58,
    INJECTION_GPMSUPPORT                           = 59,
    INJECTION_GPMSUPPORT_PTR                       = 60,
    INJECTION_GPUDYNAMICPSTATESINFO                = 61,
    INJECTION_GPUDYNAMICPSTATESINFO_PTR            = 62,
    INJECTION_GPUINSTANCEINFO                      = 63,
    INJECTION_GPUINSTANCEINFO_PTR                  = 64,
    INJECTION_GPUINSTANCEPLACEMENT                 = 65,
    INJECTION_GPUINSTANCEPLACEMENT_PTR             = 66,
    INJECTION_GPUINSTANCEPROFILEINFO               = 67,
    INJECTION_GPUINSTANCEPROFILEINFO_PTR           = 68,
    INJECTION_GPUINSTANCEPROFILEINFO_V2            = 69,
    INJECTION_GPUINSTANCEPROFILEINFO_V2_PTR        = 70,
    INJECTION_GPUINSTANCE                          = 71,
    INJECTION_GPUINSTANCE_PTR                      = 72,
    INJECTION_GPUOPERATIONMODE                     = 73,
    INJECTION_GPUOPERATIONMODE_PTR                 = 74,
    INJECTION_GPUP2PCAPSINDEX                      = 75,
    INJECTION_GPUP2PSTATUS                         = 76,
    INJECTION_GPUP2PSTATUS_PTR                     = 77,
    INJECTION_GPUTHERMALSETTINGS                   = 78,
    INJECTION_GPUTHERMALSETTINGS_PTR               = 79,
    INJECTION_GPUTOPOLOGYLEVEL                     = 80,
    INJECTION_GPUTOPOLOGYLEVEL_PTR                 = 81,
    INJECTION_GPUVIRTUALIZATIONMODE                = 82,
    INJECTION_GPUVIRTUALIZATIONMODE_PTR            = 83,
    INJECTION_GRIDLICENSABLEFEATURES               = 84,
    INJECTION_GRIDLICENSABLEFEATURES_PTR           = 85,
    INJECTION_HOSTVGPUMODE                         = 86,
    INJECTION_HOSTVGPUMODE_PTR                     = 87,
    INJECTION_HWBCENTRY                            = 88,
    INJECTION_HWBCENTRY_PTR                        = 89,
    INJECTION_INFOROMOBJECT                        = 90,
    INJECTION_INTNVLINKDEVICETYPE                  = 91,
    INJECTION_INTNVLINKDEVICETYPE_PTR              = 92,
    INJECTION_LEDCOLOR                             = 93,
    INJECTION_LEDSTATE                             = 94,
    INJECTION_LEDSTATE_PTR                         = 95,
    INJECTION_MEMORYERRORTYPE                      = 96,
    INJECTION_MEMORYLOCATION                       = 97,
    INJECTION_MEMORY                               = 98,
    INJECTION_MEMORY_PTR                           = 99,
    INJECTION_MEMORY_V2                            = 100,
    INJECTION_MEMORY_V2_PTR                        = 101,
    INJECTION_NVLINKCAPABILITY                     = 102,
    INJECTION_NVLINKERRORCOUNTER                   = 103,
    INJECTION_NVLINKUTILIZATIONCONTROL             = 104,
    INJECTION_NVLINKUTILIZATIONCONTROL_PTR         = 105,
    INJECTION_PSUINFO                              = 106,
    INJECTION_PSUINFO_PTR                          = 107,
    INJECTION_PAGERETIREMENTCAUSE                  = 108,
    INJECTION_PCIINFO                              = 109,
    INJECTION_PCIINFO_PTR                          = 110,
    INJECTION_PCIELINKSTATE                        = 111,
    INJECTION_PCIEUTILCOUNTER                      = 112,
    INJECTION_PERFPOLICYTYPE                       = 113,
    INJECTION_PROCESSINFO                          = 114,
    INJECTION_PROCESSINFO_PTR                      = 115,
    INJECTION_PROCESSINFO_V1                       = 116,
    INJECTION_PROCESSINFO_V1_PTR                   = 117,
    INJECTION_PROCESSINFO_V2                       = 118,
    INJECTION_PROCESSINFO_V2_PTR                   = 119,
    INJECTION_PROCESSUTILIZATIONSAMPLE             = 120,
    INJECTION_PROCESSUTILIZATIONSAMPLE_PTR         = 121,
    INJECTION_PSTATES                              = 122,
    INJECTION_PSTATES_PTR                          = 123,
    INJECTION_RESTRICTEDAPI                        = 124,
    INJECTION_RETURN                               = 125,
    INJECTION_RETURN_PTR                           = 126,
    INJECTION_ROWREMAPPERHISTOGRAMVALUES           = 127,
    INJECTION_ROWREMAPPERHISTOGRAMVALUES_PTR       = 128,
    INJECTION_SAMPLE                               = 129,
    INJECTION_SAMPLE_PTR                           = 130,
    INJECTION_SAMPLINGTYPE                         = 131,
    INJECTION_TEMPERATURESENSORS                   = 132,
    INJECTION_TEMPERATURETHRESHOLDS                = 133,
    INJECTION_UNITFANSPEEDS                        = 134,
    INJECTION_UNITFANSPEEDS_PTR                    = 135,
    INJECTION_UNITINFO                             = 136,
    INJECTION_UNITINFO_PTR                         = 137,
    INJECTION_UNIT                                 = 138,
    INJECTION_UNIT_PTR                             = 139,
    INJECTION_UTILIZATION                          = 140,
    INJECTION_UTILIZATION_PTR                      = 141,
    INJECTION_VALUETYPE                            = 142,
    INJECTION_VALUETYPE_PTR                        = 143,
    INJECTION_VGPUCAPABILITY                       = 144,
    INJECTION_VGPUINSTANCEUTILIZATIONSAMPLE        = 145,
    INJECTION_VGPUINSTANCEUTILIZATIONSAMPLE_PTR    = 146,
    INJECTION_VGPULICENSEINFO                      = 147,
    INJECTION_VGPULICENSEINFO_PTR                  = 148,
    INJECTION_VGPUMETADATA                         = 149,
    INJECTION_VGPUMETADATA_PTR                     = 150,
    INJECTION_VGPUPGPUCOMPATIBILITY                = 151,
    INJECTION_VGPUPGPUCOMPATIBILITY_PTR            = 152,
    INJECTION_VGPUPGPUMETADATA                     = 153,
    INJECTION_VGPUPGPUMETADATA_PTR                 = 154,
    INJECTION_VGPUPROCESSUTILIZATIONSAMPLE         = 155,
    INJECTION_VGPUPROCESSUTILIZATIONSAMPLE_PTR     = 156,
    INJECTION_VGPUVERSION                          = 157,
    INJECTION_VGPUVERSION_PTR                      = 158,
    INJECTION_VGPUVMIDTYPE                         = 159,
    INJECTION_VGPUVMIDTYPE_PTR                     = 160,
    INJECTION_VIOLATIONTIME                        = 161,
    INJECTION_VIOLATIONTIME_PTR                    = 162,
    INJECTION_UINT                                 = 163,
    INJECTION_UINT_PTR                             = 164,
    INJECTION_ULONG                                = 165,
    INJECTION_ULONG_PTR                            = 166,
    INJECTION_ULONG_LONG                           = 167,
    INJECTION_ULONG_LONG_PTR                       = 168,
    INJECTION_STRING                               = 169,
    InjectionArgCount
} injectionArgType_t;

typedef struct
{
    simpleValue_t value;
    injectionArgType_t type;
} injectNvmlVal_t;
