#!/usr/bin/env bash
set -euxo pipefail

DIR=$(dirname $(realpath $0))
TARGET_CL="28829141"
DRV_VERSION=450.51.06
BUILD_TYPE=release
RELEASE_DIR=${P4_ROOT}/sw/rel/gpu_drv/r450/r451_40

pushd ${RELEASE_DIR}

# Bail if opened files
p4 opened ./... 2>&1 | egrep -q 'not opened on this client'

# Sync everything under release directory to target CL
p4 sync -f ./...@${TARGET_CL}

cd ${RELEASE_DIR}/apps/nvswitch/nscq
rm -rf _out

# Patch wrong soname
patch < ${DIR}/patches/28597733.patch

unix-build nvmake ${BUILD_TYPE} amd64
cp _out/Linux_amd64_${BUILD_TYPE}/libnvidia-nscq.so.${DRV_VERSION} ${DIR}/lib/x64/libnvidia-nscq-dcgm.so.${DRV_VERSION}

cd ${DIR}/lib/x64
ln -sf libnvidia-nscq-dcgm.so.${DRV_VERSION} libnvidia-nscq-dcgm.so.1.0

popd
