// Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =========================================================
// THIS FILE HAS BEEN AUTOGENERATED! DO NOT MODIFY MANUALLY!
// =========================================================

#pragma once

#if __has_include("DcgmVgpuOps.h")
#include "DcgmVgpuOps.h"
#elif __has_include("DcgmVgpuOps.hpp")
#include "DcgmVgpuOps.hpp"
#else
#error "Could not find DcgmVgpuOps header"
#endif
#include <cassert>

// clang-format off

class FbcSessionOpsAnyPtr
{
public:
    // Constructor/Destructor
    template <class T>
    FbcSessionOpsAnyPtr(T *pT)
    {
        m_pVoid = pT;

        static constexpr VTable vTable = {
            // Forward arguments to type's functions
            [](void  *pStorage, NvmlTaskRunner & nvmlDriver, SafeNvmlHandle safeNvmlDevice, unsigned int * sessionCount, nvmlFBCSessionInfo_t * sessionInfo) -> nvmlReturn_t {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->NvmlDeviceGetFBCSessions(std::forward<decltype(nvmlDriver)>(nvmlDriver), std::forward<decltype(safeNvmlDevice)>(safeNvmlDevice), std::forward<decltype(sessionCount)>(sessionCount), std::forward<decltype(sessionInfo)>(sessionInfo));
            },
            [](void  *pStorage, NvmlTaskRunner & nvmlDriver, SafeVgpuInstance vgpuId, unsigned int * sessionCount, nvmlFBCSessionInfo_t * sessionInfo) -> nvmlReturn_t {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->NvmlVgpuInstanceGetFBCSessions(std::forward<decltype(nvmlDriver)>(nvmlDriver), std::forward<decltype(vgpuId)>(vgpuId), std::forward<decltype(sessionCount)>(sessionCount), std::forward<decltype(sessionInfo)>(sessionInfo));
            },
            [](void  *pStorage, std::size_t size) -> void * {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->Malloc(std::forward<decltype(size)>(size));
            },
            [](void  *pStorage, void * ptr) -> void {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->Free(std::forward<decltype(ptr)>(ptr));
            },
            [](void  *pStorage, DcgmCacheManager & cm, dcgmcm_update_thread_t & threadCtx, void * value, int valueSize, timelib64_t timestamp, timelib64_t oldestKeepTimestamp) -> dcgmReturn_t {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->AppendEntityBlob(std::forward<decltype(cm)>(cm), std::forward<decltype(threadCtx)>(threadCtx), std::forward<decltype(value)>(value), std::forward<decltype(valueSize)>(valueSize), std::forward<decltype(timestamp)>(timestamp), std::forward<decltype(oldestKeepTimestamp)>(oldestKeepTimestamp));
            },
            [](void  *pStorage, nvmlReturn_t nvmlReturn) -> dcgmReturn_t {
                auto *pT = *reinterpret_cast<T  **>(pStorage);
                return pT->NvmlReturnToDcgmReturn(std::forward<decltype(nvmlReturn)>(nvmlReturn));
            },
            };
        m_pVTable = &vTable;
    }
    ~FbcSessionOpsAnyPtr()
    {
    }

    // Copy/Move operations
    FbcSessionOpsAnyPtr(FbcSessionOpsAnyPtr const &other)
        : m_pVTable(other.m_pVTable)
        , m_pVoid(other.m_pVoid)
    {
    }
    FbcSessionOpsAnyPtr &operator=(FbcSessionOpsAnyPtr const &other)
    {
        // Stored types must match
        assert(m_pVTable == other.m_pVTable);
        m_pVoid = other.m_pVoid;
        return *this;
    }
    FbcSessionOpsAnyPtr(FbcSessionOpsAnyPtr &&other) noexcept
        : m_pVTable(other.m_pVTable)
        , m_pVoid(other.m_pVoid)
    {
    }
    FbcSessionOpsAnyPtr &operator=(FbcSessionOpsAnyPtr &&other) noexcept
    {
        // Stored types must match
        assert(m_pVTable == other.m_pVTable);
        m_pVoid = other.m_pVoid;
        return *this;
    }

    // Comparison operations
    bool operator==(FbcSessionOpsAnyPtr const &other) const
    {
        assert(m_pVTable == other.m_pVTable);
        return m_pVoid == other.m_pVoid;
    }
    bool operator!=(FbcSessionOpsAnyPtr const &other) const
    {
        return !(*this == other);
    }
    bool operator==(std::nullptr_t other) const
    {
        return m_pVoid == other;
    }
    bool operator!=(std::nullptr_t other) const
    {
        return !(*this == other);
    }

    // -> operations to emulate pointer behavior
    FbcSessionOpsAnyPtr *operator->()
    {
        return this;
    }
    FbcSessionOpsAnyPtr const *operator->() const
    {
        return this;
    }

    // Declare type's functions
    nvmlReturn_t NvmlDeviceGetFBCSessions(NvmlTaskRunner & nvmlDriver, SafeNvmlHandle safeNvmlDevice, unsigned int * sessionCount, nvmlFBCSessionInfo_t * sessionInfo)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->NvmlDeviceGetFBCSessions0(&m_pVoid, std::forward<decltype(nvmlDriver)>(nvmlDriver), std::forward<decltype(safeNvmlDevice)>(safeNvmlDevice), std::forward<decltype(sessionCount)>(sessionCount), std::forward<decltype(sessionInfo)>(sessionInfo));
    }
    nvmlReturn_t NvmlVgpuInstanceGetFBCSessions(NvmlTaskRunner & nvmlDriver, SafeVgpuInstance vgpuId, unsigned int * sessionCount, nvmlFBCSessionInfo_t * sessionInfo)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->NvmlVgpuInstanceGetFBCSessions0(&m_pVoid, std::forward<decltype(nvmlDriver)>(nvmlDriver), std::forward<decltype(vgpuId)>(vgpuId), std::forward<decltype(sessionCount)>(sessionCount), std::forward<decltype(sessionInfo)>(sessionInfo));
    }
    void * Malloc(std::size_t size)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->Malloc0(&m_pVoid, std::forward<decltype(size)>(size));
    }
    void Free(void * ptr)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->Free0(&m_pVoid, std::forward<decltype(ptr)>(ptr));
    }
    dcgmReturn_t AppendEntityBlob(DcgmCacheManager & cm, dcgmcm_update_thread_t & threadCtx, void * value, int valueSize, timelib64_t timestamp, timelib64_t oldestKeepTimestamp)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->AppendEntityBlob0(&m_pVoid, std::forward<decltype(cm)>(cm), std::forward<decltype(threadCtx)>(threadCtx), std::forward<decltype(value)>(value), std::forward<decltype(valueSize)>(valueSize), std::forward<decltype(timestamp)>(timestamp), std::forward<decltype(oldestKeepTimestamp)>(oldestKeepTimestamp));
    }
    dcgmReturn_t NvmlReturnToDcgmReturn(nvmlReturn_t nvmlReturn)  
    {
        // Regardless of the type stored, we always pass in the pointer to our
        // buffer. The VTable encodes instructions on how to interpret that
        // pointer
        return m_pVTable->NvmlReturnToDcgmReturn0(&m_pVoid, std::forward<decltype(nvmlReturn)>(nvmlReturn));
    }
    
private:
    struct VTable
    {
        // Declare type's functions
        nvmlReturn_t (*NvmlDeviceGetFBCSessions0)(void  *, NvmlTaskRunner &, SafeNvmlHandle, unsigned int *, nvmlFBCSessionInfo_t *);
        nvmlReturn_t (*NvmlVgpuInstanceGetFBCSessions0)(void  *, NvmlTaskRunner &, SafeVgpuInstance, unsigned int *, nvmlFBCSessionInfo_t *);
        void * (*Malloc0)(void  *, std::size_t);
        void (*Free0)(void  *, void *);
        dcgmReturn_t (*AppendEntityBlob0)(void  *, DcgmCacheManager &, dcgmcm_update_thread_t &, void *, int, timelib64_t, timelib64_t);
        dcgmReturn_t (*NvmlReturnToDcgmReturn0)(void  *, nvmlReturn_t);
        
    };

    VTable const *m_pVTable;
    void *m_pVoid;
};

// clang-format on

// =========================================================
// THIS FILE HAS BEEN AUTOGENERATED! DO NOT MODIFY MANUALLY!
// =========================================================
