/*
 * Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <catch2/catch_all.hpp>

#include <array>

// Opt into deprecated aliases so this compatibility test runs in source-tree builds
#undef DCGM_DEPRECATED
#define DCGM_DEPRECATED 1
#include <dcgm_fields.h>
#include <dcgm_fields_internal.hpp>
#include <dcgm_nvml.h>


TEST_CASE("dcgm_fields: deprecated aliases resolve to canonical field IDs")
{
    // REQUIRE(DEPRECATED == CANONICAL)
    REQUIRE(DCGM_FI_UNKNOWN == DCGM_FI_SYSTEM_FIELD_UNKNOWN);
    REQUIRE(DCGM_FI_DRIVER_VERSION == DCGM_FI_SYSTEM_DRIVER_VERSION);
    REQUIRE(DCGM_FI_NVML_VERSION == DCGM_FI_SYSTEM_NVML_VERSION);
    REQUIRE(DCGM_FI_PROCESS_NAME == DCGM_FI_SYSTEM_PROCESS_NAME);
    REQUIRE(DCGM_FI_DEV_COUNT == DCGM_FI_SYSTEM_GPU_QUANTITY);
    REQUIRE(DCGM_FI_BIND_UNBIND_EVENT == DCGM_FI_SYSTEM_GPU_BIND_EVENT);
    REQUIRE(DCGM_FI_DEV_NAME == DCGM_FI_DEV_GPU_NAME);
    REQUIRE(DCGM_FI_DEV_BRAND == DCGM_FI_DEV_GPU_BRAND);
    REQUIRE(DCGM_FI_DEV_SERIAL == DCGM_FI_DEV_BOARD_SERIAL);
    REQUIRE(DCGM_FI_DEV_UUID == DCGM_FI_DEV_GPU_UUID);
    REQUIRE(DCGM_FI_DEV_MINOR_NUMBER == DCGM_FI_DEV_GPU_MINOR_NUMBER);
    REQUIRE(DCGM_FI_DEV_OEM_INFOROM_VER == DCGM_FI_DEV_INFOROM_OEM_VERSION);
    REQUIRE(DCGM_FI_DEV_PCI_BUSID == DCGM_FI_DEV_PCI_BUS_ID);
    REQUIRE(DCGM_FI_GPU_TOPOLOGY_PCI == DCGM_FI_SYSTEM_PCI_TOPOLOGY);
    REQUIRE(DCGM_FI_GPU_TOPOLOGY_NVLINK == DCGM_FI_SYSTEM_NVLINK_TOPOLOGY);
    REQUIRE(DCGM_FI_GPU_TOPOLOGY_AFFINITY == DCGM_FI_SYSTEM_GPU_AFFINITY);
    REQUIRE(DCGM_FI_DEV_CUDA_COMPUTE_CAPABILITY == DCGM_FI_CUDA_GPU_COMPUTE_CAPABILITY);
    REQUIRE(DCGM_FI_DEV_P2P_NVLINK_STATUS == DCGM_FI_DEV_NVLINK_P2P_STATUS);
    REQUIRE(DCGM_FI_DEV_COMPUTE_MODE == DCGM_FI_DEV_GPU_COMPUTE_MODE);
    REQUIRE(DCGM_FI_DEV_PERSISTENCE_MODE == DCGM_FI_DEV_GPU_PERSISTENCE_MODE);
    REQUIRE(DCGM_FI_DEV_CUDA_VISIBLE_DEVICES_STR == DCGM_FI_CUDA_GPU_VISIBLE_DEVICES);
    REQUIRE(DCGM_FI_DEV_ECC_INFOROM_VER == DCGM_FI_DEV_INFOROM_ECC_VERSION);
    REQUIRE(DCGM_FI_DEV_POWER_INFOROM_VER == DCGM_FI_DEV_INFOROM_POWER_VERSION);
    REQUIRE(DCGM_FI_DEV_INFOROM_IMAGE_VER == DCGM_FI_DEV_INFOROM_IMAGE_VERSION);
    REQUIRE(DCGM_FI_DEV_INFOROM_CONFIG_CHECK == DCGM_FI_DEV_INFOROM_CHECKSUM);
    REQUIRE(DCGM_FI_DEV_INFOROM_CONFIG_VALID == DCGM_FI_DEV_INFOROM_VALID);
    REQUIRE(DCGM_FI_DEV_MEM_AFFINITY_0 == DCGM_FI_DEV_MEMORY_AFFINITY_0);
    REQUIRE(DCGM_FI_DEV_MEM_AFFINITY_1 == DCGM_FI_DEV_MEMORY_AFFINITY_1);
    REQUIRE(DCGM_FI_DEV_MEM_AFFINITY_2 == DCGM_FI_DEV_MEMORY_AFFINITY_2);
    REQUIRE(DCGM_FI_DEV_MEM_AFFINITY_3 == DCGM_FI_DEV_MEMORY_AFFINITY_3);
    REQUIRE(DCGM_FI_SYNC_BOOST == DCGM_FI_SYSTEM_GPU_SYNC_BOOST);
    REQUIRE(DCGM_FI_DEV_AUTOBOOST == DCGM_FI_DEV_CLOCKS_AUTOBOOST_MODE);
    REQUIRE(DCGM_FI_DEV_SUPPORTED_CLOCKS == DCGM_FI_DEV_CLOCKS_SUPPORTED);
    REQUIRE(DCGM_FI_DEV_MEMORY_TEMP == DCGM_FI_DEV_MEMORY_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_GPU_TEMP == DCGM_FI_DEV_GPU_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_MEM_MAX_OP_TEMP == DCGM_FI_DEV_MEMORY_MAX_OP_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_GPU_MAX_OP_TEMP == DCGM_FI_DEV_GPU_MAX_OP_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_GPU_TEMP_LIMIT == DCGM_FI_DEV_GPU_TEMP_MARGIN_CELSIUS);
    REQUIRE(DCGM_FI_DEV_POWER_USAGE == DCGM_FI_DEV_BOARD_POWER_WATTS);
    REQUIRE(DCGM_FI_DEV_POWER_USAGE_INSTANT == DCGM_FI_DEV_BOARD_POWER_RAW_WATTS);
    REQUIRE(DCGM_FI_DEV_SLOWDOWN_TEMP == DCGM_FI_DEV_GPU_TEMP_SLOWDOWN_CELSIUS);
    REQUIRE(DCGM_FI_DEV_SHUTDOWN_TEMP == DCGM_FI_DEV_GPU_TEMP_SHUTDOWN_CELSIUS);
    REQUIRE(DCGM_FI_DEV_POWER_MGMT_LIMIT == DCGM_FI_DEV_BOARD_POWER_LIMIT_REQUESTED_WATTS);
    REQUIRE(DCGM_FI_DEV_POWER_MGMT_LIMIT_MIN == DCGM_FI_DEV_BOARD_POWER_LIMIT_MIN_WATTS);
    REQUIRE(DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX == DCGM_FI_DEV_BOARD_POWER_LIMIT_MAX_WATTS);
    REQUIRE(DCGM_FI_DEV_POWER_MGMT_LIMIT_DEF == DCGM_FI_DEV_BOARD_POWER_LIMIT_DEFAULT_WATTS);
    REQUIRE(DCGM_FI_DEV_ENFORCED_POWER_LIMIT == DCGM_FI_DEV_BOARD_POWER_LIMIT_ENFORCED_WATTS);
    REQUIRE(DCGM_FI_DEV_REQUESTED_POWER_PROFILE_MASK == DCGM_FI_DEV_BOARD_POWER_PROFILE_REQUESTED_MASK);
    REQUIRE(DCGM_FI_DEV_ENFORCED_POWER_PROFILE_MASK == DCGM_FI_DEV_BOARD_POWER_PROFILE_ENFORCED_MASK);
    REQUIRE(DCGM_FI_DEV_VALID_POWER_PROFILE_MASK == DCGM_FI_DEV_BOARD_POWER_PROFILE_SUPPORTED_MASK);
    REQUIRE(DCGM_FI_DEV_FABRIC_MANAGER_ERROR_CODE == DCGM_FI_DEV_FABRIC_MANAGER_ERROR);
    REQUIRE(DCGM_FI_DEV_PSTATE == DCGM_FI_DEV_GPU_PSTATE);
    REQUIRE(DCGM_FI_DEV_PCIE_REPLAY_COUNTER == DCGM_FI_DEV_PCIE_REPLAY_TOTAL);
    REQUIRE(DCGM_FI_DEV_GPU_UTIL == DCGM_FI_DEV_GPU_UTIL_RATIO);
    REQUIRE(DCGM_FI_DEV_XID_ERRORS == DCGM_FI_DEV_XID_ERROR);
    REQUIRE(DCGM_FI_DEV_ECC_CURRENT == DCGM_FI_DEV_ECC_MODE);
    REQUIRE(DCGM_FI_DEV_THRESHOLD_SRM == DCGM_FI_DEV_SRAM_EXCEEDED);
    REQUIRE(DCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_MAX == DCGM_FI_DEV_BANK_REMAP_AVAIL_MAX);
    REQUIRE(DCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_HIGH == DCGM_FI_DEV_BANK_REMAP_AVAIL_HIGH);
    REQUIRE(DCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_PARTIAL == DCGM_FI_DEV_BANK_REMAP_AVAIL_PARTIAL);
    REQUIRE(DCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_LOW == DCGM_FI_DEV_BANK_REMAP_AVAIL_LOW);
    REQUIRE(DCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_NONE == DCGM_FI_DEV_BANK_REMAP_AVAIL_NONE);
    REQUIRE(DCGM_FI_DEV_RETIRED_SBE == DCGM_FI_DEV_PAGE_RETIRED_SBE_TOTAL);
    REQUIRE(DCGM_FI_DEV_RETIRED_DBE == DCGM_FI_DEV_PAGE_RETIRED_DBE_TOTAL);
    REQUIRE(DCGM_FI_DEV_RETIRED_PENDING == DCGM_FI_DEV_PAGE_RETIRED_PENDING);
    REQUIRE(DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS == DCGM_FI_DEV_ROW_REMAP_UNCORRECTABLE_TOTAL);
    REQUIRE(DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS == DCGM_FI_DEV_ROW_REMAP_CORRECTABLE_TOTAL);
    REQUIRE(DCGM_FI_DEV_ROW_REMAP_FAILURE == DCGM_FI_DEV_ROW_REMAP_FAILED);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L0 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L1 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L2 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L3 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L4 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L5 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L6 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L7 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L8 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L8_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L9 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L9_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L10 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L10_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L11 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L11_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L12 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L12_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L13 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L13_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L14 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L14_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L15 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L15_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L16 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L16_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L17 == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_L17_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L0 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L1 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L2 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L3 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L4 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L5 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L6 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L7 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L8 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L8_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L9 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L9_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L10 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L10_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L11 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L11_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L12 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L12_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L13 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L13_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L14 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L14_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L15 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L15_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L16 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L16_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L17 == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_L17_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L0 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L1 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L2 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L3 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L4 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L5 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L6 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L7 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L8 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L8_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L9 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L9_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L10 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L10_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L11 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L11_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L12 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L12_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L13 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L13_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L14 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L14_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L15 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L15_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L16 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L16_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L17 == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_L17_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L0 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L1 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L2 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L3 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L4 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L5 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L6 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L7 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L8 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L8_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L9 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L9_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L10 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L10_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L11 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L11_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L12 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L12_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L13 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L13_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L14 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L14_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L15 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L15_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L16 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L16_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L17 == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_L17_TOTAL);
    REQUIRE(DCGM_FI_DEV_GPU_NVLINK_ERRORS == DCGM_FI_DEV_NVLINK_ERROR);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL == DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL == DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL == DCGM_FI_DEV_NVLINK_REPLAY_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL == DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_ERROR_DL_CRC == DCGM_FI_DEV_NVLINK_CRC_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_ERROR_DL_RECOVERY == DCGM_FI_DEV_NVLINK_RECOVERY_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_ERROR_DL_REPLAY == DCGM_FI_DEV_NVLINK_REPLAY_TOTAL);
    REQUIRE(DCGM_FI_DEV_VIRTUAL_MODE == DCGM_FI_DEV_GPU_VIRTUAL_MODE);
    REQUIRE(DCGM_FI_DEV_SUPPORTED_TYPE_INFO == DCGM_FI_DEV_VGPU_SUPPORTED_INFO);
    REQUIRE(DCGM_FI_DEV_CREATABLE_VGPU_TYPE_IDS == DCGM_FI_DEV_VGPU_CREATABLE_IDS);
    REQUIRE(DCGM_FI_DEV_VGPU_INSTANCE_IDS == DCGM_FI_DEV_VGPU_INSTANCE_INFO);
    REQUIRE(DCGM_FI_DEV_VGPU_UTILIZATIONS == DCGM_FI_DEV_VGPU_UTIL_INFO);
    REQUIRE(DCGM_FI_DEV_VGPU_PER_PROCESS_UTILIZATION == DCGM_FI_DEV_VGPU_PROCESS_UTIL_INFO);
    REQUIRE(DCGM_FI_DEV_SUPPORTED_VGPU_TYPE_IDS == DCGM_FI_DEV_VGPU_SUPPORTED_IDS);
    REQUIRE(DCGM_FI_DEV_VGPU_INSTANCE_LICENSE_STATE == DCGM_FI_DEV_VGPU_INSTANCE_LICENSE_STATUS);
    REQUIRE(DCGM_FI_DEV_VGPU_VM_GPU_INSTANCE_ID == DCGM_FI_DEV_VGPU_GPU_INSTANCE_ID);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_RECOVERY_TOTAL_SUCCESSFUL_EVENTS
            == DCGM_FI_DEV_NVLINK_PPCNT_RECOVERY_SUCCESSFUL_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PHYSICAL_SUCCESSFUL_RECOVERY_EVENTS
            == DCGM_FI_DEV_NVLINK_PPCNT_PHYSICAL_RECOVERY_SUCCESSFUL_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PHYSICAL_LINK_DOWN_COUNTER == DCGM_FI_DEV_NVLINK_PPCNT_PHYSICAL_LINK_DOWN_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_RCV_CODES == DCGM_FI_DEV_NVLINK_PPCNT_PLR_RX_CODE_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_RCV_CODE_ERR == DCGM_FI_DEV_NVLINK_PPCNT_PLR_RX_CODE_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_RCV_UNCORRECTABLE_CODE
            == DCGM_FI_DEV_NVLINK_PPCNT_PLR_RX_CODE_UNCORRECTABLE_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_XMIT_CODES == DCGM_FI_DEV_NVLINK_PPCNT_PLR_TX_CODE_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_XMIT_RETRY_CODES == DCGM_FI_DEV_NVLINK_PPCNT_PLR_TX_RETRY_CODE_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_XMIT_RETRY_EVENTS == DCGM_FI_DEV_NVLINK_PPCNT_PLR_TX_RETRY_EVENT_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_PPCNT_PLR_SYNC_EVENTS == DCGM_FI_DEV_NVLINK_PPCNT_PLR_SYNC_EVENT_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_POWER_VDD == DCGM_FI_DEV_NVSWITCH_POWER_VDD_WATTS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_POWER_DVDD == DCGM_FI_DEV_NVSWITCH_POWER_DVDD_WATTS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_POWER_HVDD == DCGM_FI_DEV_NVSWITCH_POWER_HVDD_WATTS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_REPLAY_ERRORS == DCGM_FI_DEV_NVSWITCH_LINK_REPLAY_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_RECOVERY_ERRORS == DCGM_FI_DEV_NVSWITCH_LINK_RECOVERY_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_FLIT_ERRORS == DCGM_FI_DEV_NVSWITCH_LINK_FLIT_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC0 == DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_SAMPLE_VC0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC1 == DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_SAMPLE_VC1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC2 == DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_SAMPLE_VC2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC3 == DCGM_FI_DEV_NVSWITCH_LINK_LATENCY_SAMPLE_VC3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE0 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE1 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE2 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE3 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE4 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE5 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE6 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE7 == DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE0 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L0_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE1 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L1_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE2 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L2_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE3 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L3_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE4 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L4_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE5 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L5_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE6 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L6_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE7 == DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERROR_L7_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_TEMPERATURE_CURRENT == DCGM_FI_DEV_NVSWITCH_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SLOWDOWN == DCGM_FI_DEV_NVSWITCH_TEMP_SLOWDOWN_CELSIUS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SHUTDOWN == DCGM_FI_DEV_NVSWITCH_TEMP_SHUTDOWN_CELSIUS);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_PHYS_ID == DCGM_FI_DEV_NVSWITCH_PHYSICAL_ID);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_FATAL_ERRORS == DCGM_FI_DEV_SXID_FATAL_ERROR);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_NON_FATAL_ERRORS == DCGM_FI_DEV_SXID_NON_FATAL_ERROR);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_DEVICE_LINK_ID == DCGM_FI_DEV_NVSWITCH_LINK_REMOTE_LINK_ID);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_LINK_DEVICE_LINK_SID == DCGM_FI_DEV_NVSWITCH_LINK_REMOTE_LINK_SID);
    REQUIRE(DCGM_FI_DEV_NVSWITCH_DEVICE_UUID == DCGM_FI_DEV_NVSWITCH_UUID);
    REQUIRE(DCGM_FI_PROF_GR_ENGINE_ACTIVE == DCGM_FI_PROF_GR_ENGINE_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_SM_ACTIVE == DCGM_FI_PROF_SM_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_SM_OCCUPANCY == DCGM_FI_PROF_SM_OCCUPANCY_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE == DCGM_FI_PROF_TENSOR_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_DRAM_ACTIVE == DCGM_FI_PROF_DRAM_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_FP64_ACTIVE == DCGM_FI_PROF_FP64_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_FP32_ACTIVE == DCGM_FI_PROF_FP32_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_FP16_ACTIVE == DCGM_FI_PROF_FP16_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_TENSOR_IMMA_ACTIVE == DCGM_FI_PROF_IMMA_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_TENSOR_HMMA_ACTIVE == DCGM_FI_PROF_HMMA_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_TENSOR_DFMA_ACTIVE == DCGM_FI_PROF_DFMA_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_PIPE_INT_ACTIVE == DCGM_FI_PROF_INT_UTIL_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC0_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_0_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC1_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_1_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC2_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_2_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC3_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_3_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC4_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_4_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC5_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_5_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC6_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_6_RATIO);
    REQUIRE(DCGM_FI_PROF_NVDEC7_ACTIVE == DCGM_FI_PROF_NVDEC_UTIL_7_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG0_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_0_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG1_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_1_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG2_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_2_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG3_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_3_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG4_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_4_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG5_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_5_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG6_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_6_RATIO);
    REQUIRE(DCGM_FI_PROF_NVJPG7_ACTIVE == DCGM_FI_PROF_NVJPG_UTIL_7_RATIO);
    REQUIRE(DCGM_FI_PROF_NVOFA0_ACTIVE == DCGM_FI_PROF_NVOFA_UTIL_0_RATIO);
    REQUIRE(DCGM_FI_PROF_NVOFA1_ACTIVE == DCGM_FI_PROF_NVOFA_UTIL_1_RATIO);
    REQUIRE(DCGM_FI_DEV_CPU_TEMP_CURRENT == DCGM_FI_DEV_CPU_TEMP_CELSIUS);
    REQUIRE(DCGM_FI_DEV_CPU_TEMP_WARNING == DCGM_FI_DEV_CPU_TEMP_WARNING_CELSIUS);
    REQUIRE(DCGM_FI_DEV_CPU_TEMP_CRITICAL == DCGM_FI_DEV_CPU_TEMP_CRITICAL_CELSIUS);
    REQUIRE(DCGM_FI_DEV_CPU_POWER_UTIL_CURRENT == DCGM_FI_DEV_CPU_POWER_WATTS);
    REQUIRE(DCGM_FI_DEV_CPU_POWER_LIMIT == DCGM_FI_DEV_CPU_POWER_LIMIT_WATTS);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_TX_PACKETS == DCGM_FI_DEV_NVLINK_TX_PACKET_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_TX_BYTES == DCGM_FI_DEV_NVLINK_TX_BYTES_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_PACKETS == DCGM_FI_DEV_NVLINK_RX_PACKET_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_BYTES == DCGM_FI_DEV_NVLINK_RX_BYTES_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_MALFORMED_PACKET_ERRORS == DCGM_FI_DEV_NVLINK_RX_PACKET_MALFORMED_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_BUFFER_OVERRUN_ERRORS == DCGM_FI_DEV_NVLINK_RX_PACKET_DROPPED_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_ERRORS == DCGM_FI_DEV_NVLINK_RX_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_REMOTE_ERRORS == DCGM_FI_DEV_NVLINK_RX_REMOTE_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_GENERAL_ERRORS == DCGM_FI_DEV_NVLINK_RX_GENERAL_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_LOCAL_LINK_INTEGRITY_ERRORS == DCGM_FI_DEV_NVLINK_INTEGRITY_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_LINK_RECOVERY_SUCCESSFUL_EVENTS == DCGM_FI_DEV_NVLINK_RECOVERY_SUCCESSFUL_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_LINK_RECOVERY_FAILED_EVENTS == DCGM_FI_DEV_NVLINK_RECOVERY_FAILED_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_LINK_RECOVERY_EVENTS == DCGM_FI_DEV_NVLINK_RECOVERY_EVENT_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_RX_SYMBOL_ERRORS == DCGM_FI_DEV_NVLINK_RX_SYMBOL_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_SYMBOL_BER == DCGM_FI_DEV_NVLINK_SYMBOL_BER_RAW);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_SYMBOL_BER_FLOAT == DCGM_FI_DEV_NVLINK_SYMBOL_BER_RATIO);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_EFFECTIVE_BER == DCGM_FI_DEV_NVLINK_EFFECTIVE_BER_RAW);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_EFFECTIVE_BER_FLOAT == DCGM_FI_DEV_NVLINK_EFFECTIVE_BER_RATIO);
    REQUIRE(DCGM_FI_DEV_NVLINK_COUNT_EFFECTIVE_ERRORS == DCGM_FI_DEV_NVLINK_EFFECTIVE_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_NVLINK_ECC_DATA_ERROR_COUNT_TOTAL == DCGM_FI_DEV_NVLINK_ECC_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERR_STATUS == DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERROR_STATUS);
    REQUIRE(DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERR_MASK == DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERROR_MASK);
    REQUIRE(DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERR_SEVERITY == DCGM_FI_DEV_CONNECTX_UNCORRECTABLE_ERROR_SEVERITY);
    REQUIRE(DCGM_FI_DEV_PCIE_COUNT_CORRECTABLE_ERRORS == DCGM_FI_DEV_PCIE_CORRECTABLE_ERROR_TOTAL);
    REQUIRE(DCGM_FI_DEV_MEMORY_UNREPAIRABLE_FLAG == DCGM_FI_DEV_MEMORY_UNREPAIRABLE);
    REQUIRE(DCGM_FI_DEV_GET_GPU_RECOVERY_ACTION == DCGM_FI_DEV_GPU_RECOVERY_ACTION);
}

TEST_CASE("dcgm_fields: legacy NVLink profiling fields map to NVML GPM per-link bandwidth metrics")
{
    struct Mapping
    {
        unsigned int fieldId;
        unsigned int metricId;
    };

    std::array<Mapping, 4> const mappings = {
        Mapping { DCGM_FI_PROF_NVLINK_L0_TX_BYTES, NVML_GPM_METRIC_NVLINK_L0_TX_PER_SEC },
        Mapping { DCGM_FI_PROF_NVLINK_L0_RX_BYTES, NVML_GPM_METRIC_NVLINK_L0_RX_PER_SEC },
        Mapping { DCGM_FI_PROF_NVLINK_L17_TX_BYTES, NVML_GPM_METRIC_NVLINK_L17_TX_PER_SEC },
        Mapping { DCGM_FI_PROF_NVLINK_L17_RX_BYTES, NVML_GPM_METRIC_NVLINK_L17_RX_PER_SEC },
    };

    for (auto const &mapping : mappings)
    {
        CAPTURE(mapping.fieldId);

        bool isPercentageField = true;
        CHECK(DcgmFieldIdToNvmlGpmMetricId(mapping.fieldId, isPercentageField) == mapping.metricId);
        CHECK_FALSE(isPercentageField);
    }
}

TEST_CASE("dcgm_fields: per-link NVLink profiling fields resolve GPM metric from link index")
{
    struct Mapping
    {
        unsigned int linkIndex;
        unsigned int txMetricId;
        unsigned int rxMetricId;
    };

    // Links 0-17 use the original enum block; links 18-35 use the extended block.
    std::array<Mapping, 4> const mappings = {
        Mapping { 0, NVML_GPM_METRIC_NVLINK_L0_TX_PER_SEC, NVML_GPM_METRIC_NVLINK_L0_RX_PER_SEC },
        Mapping { 17, NVML_GPM_METRIC_NVLINK_L17_TX_PER_SEC, NVML_GPM_METRIC_NVLINK_L17_RX_PER_SEC },
        Mapping { 18, NVML_GPM_METRIC_NVLINK_L18_TX_PER_SEC, NVML_GPM_METRIC_NVLINK_L18_RX_PER_SEC },
        Mapping { 35, NVML_GPM_METRIC_NVLINK_L35_TX_PER_SEC, NVML_GPM_METRIC_NVLINK_L35_RX_PER_SEC },
    };

    for (auto const &mapping : mappings)
    {
        CAPTURE(mapping.linkIndex);

        bool isPercentageField = true;
        CHECK(DcgmFieldIdToNvmlGpmMetricId(DCGM_FI_PROF_NVLINK_TX_BYTES_PER_LINK, isPercentageField, mapping.linkIndex)
              == mapping.txMetricId);
        CHECK_FALSE(isPercentageField);

        CHECK(DcgmFieldIdToNvmlGpmMetricId(DCGM_FI_PROF_NVLINK_RX_BYTES_PER_LINK, isPercentageField, mapping.linkIndex)
              == mapping.rxMetricId);
        CHECK_FALSE(isPercentageField);
    }

    // Out-of-range link index returns 0 (unsupported).
    bool isPercentageField = false;
    CHECK(DcgmFieldIdToNvmlGpmMetricId(DCGM_FI_PROF_NVLINK_TX_BYTES_PER_LINK, isPercentageField, 36) == 0);
}
