alias ll='ls -alF --group-directories-first'

TERM=xterm-256color

function fx(){
    echo '##############################'
    rg \
        -Hn \
        --hidden \
        -S \
        -M 120 \
        --max-columns-preview \
        --no-messages \
        --no-heading \
        --trim \
        --column \
        --iglob='!*_out*' \
        --iglob='!.git' \
        "$@"
}
